/* ================================================================================
   Bakeweek Studio · UI, part 3: how a microbakery sells.
   Standing orders (subscriptions, wholesale, regulars) become ordinary orders four weeks ahead.
   Market days are orders baked for stock: the pieces brought, then what sold and where the leftovers went.
   ================================================================================ */
const isMarket=o=>o.kind==='market';
// what an order is worth: a closed market day counts what actually sold; anything else counts its quote
const lineSales=(o,l)=>{if(!isMarket(o)||!o.market.closed)return l.qty*l.unitPrice;const r=o.market.results.find(x=>x.recipeId===l.recipeId);return r?r.sold*l.unitPrice+(r.fate==='discounted'?r.reducedTakings:0):0;};
const linePieces=(o,l)=>isMarket(o)&&o.market.closed?(o.market.results.find(x=>x.recipeId===l.recipeId)?.sold||0):l.qty;
const sales=o=>o.lines.reduce((n,l)=>n+lineSales(o,l),0);
const CHANNELS=[['One-off orders','var(--cat-1)'],['Pre-orders','var(--cat-4)'],['Standing orders','var(--cat-3)'],['Market days','var(--cat-2)']];
const channelOf=o=>isMarket(o)?'Market days':o.standingId?'Standing orders':o.menuId?'Pre-orders':'One-off orders';
const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const joinAnd=a=>a.length<2?a.join(''):a.slice(0,-1).join(', ')+' & '+a.at(-1);
const scheduleText=so=>`${so.every===1?'Every':`Every ${so.every} weeks on`} ${joinAnd(so.days.map(d=>DAYS[d]))}`;
const leadText=n=>['same day','the day before','2 days before','3 days before'][n];
const standingOf=o=>o.standingId?state.standing.find(x=>x.id===o.standingId):null;
const standingStatus=so=>{const t=today();return so.paused?['Paused','']:so.end&&so.end<t?['Ended','']:so.start>t?['Starts '+date(so.start),'flag']:['Active','good'];};
const perDrop=so=>so.lines.reduce((n,l)=>n+l.qty*l.unitPrice,0);
const perWeek=(so,f)=>so.lines.reduce((n,l)=>n+f(l),0)*so.days.length/so.every;
const runningNow=so=>!so.paused&&(!so.end||so.end>=today());
// a market day's status, in market words
const marketLabel=s=>({Confirmed:'Planned',Ready:'Packed',Collected:'Closed',Cancelled:'Canceled'}[s]||s);
const marketPill=s=>pill(marketLabel(s),{Confirmed:'flag',Ready:'good',Collected:'',Cancelled:'warn'}[s]||'');
const kindPill=o=>isMarket(o)?pill(ico('tent')+'Market','accent'):o.standingId?pill(ico('repeat')+'Standing','accent'):o.menuId?pill(ico('note')+'Pre-order','accent'):'';
const allMade=o=>o.lines.every(l=>state.completedRuns.reduce((n,r)=>n+r.allocations.filter(a=>a.orderId===o.id&&a.recipeId===l.recipeId).reduce((k,a)=>k+a.qty,0),0)===l.qty);
const hasMade=o=>state.completedRuns.some(r=>r.allocations.some(a=>a.orderId===o.id));

// standing drops are written into the order book from today to four weeks ahead (and the week on screen):
// no undo entry, because nothing the baker did changed; undoing a standing order removes its drops with it
function autoSync(){if(!state.standing?.length)return;const from=today(),h=C.addDays(C.monday(from),27),wk=C.addDays(week,6),to=wk>h?wk:h;
 try{if(!C.missingStanding(state,from,to).length)return;C.syncStanding(state,from,to);if(!demo)save();}catch(e){console.warn('Standing drops not added:',e.message);}}

Object.assign(UI,{standing:{page:0},markets:{page:0}});

/* ---------- screens ---------- */
Object.assign(VIEWS,{
 standing(){const t=today(),all=state.standing,live=all.filter(runningNow),st=UI.standing;
  const head=pagehead('Repeat customers','Standing orders','Bread clubs, cafés and regulars. Each drop joins your order book four weeks ahead, then bakes, shops and packs like any order.',button(ico('plus')+'<span>Add standing order</span>','standing-form','primary'));
  if(!all.length)return head+`<section class="card">${empty('Set it up once, bake it every week','A bread-club subscription, a café’s twice-weekly order or a regular’s Friday loaf. Choose the days and how often, and every drop lands in your plan, shopping list and packing tickets.',button('Add a standing order','standing-form','primary'),'repeat')}</section>`;
  const weekly=live.reduce((n,so)=>n+perWeek(so,l=>l.qty*l.unitPrice),0),pieces=live.reduce((n,so)=>n+perWeek(so,l=>l.qty),0);
  const drops=state.orders.filter(o=>o.standingId&&o.dueDate>=t&&o.dueDate<=C.addDays(t,27)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.customer.localeCompare(b.customer)),next=drops.find(o=>o.status!=='Cancelled');
  const per=12,pages=Math.max(1,Math.ceil(drops.length/per));st.page=Math.max(0,Math.min(st.page,pages-1));const view=drops.slice(st.page*per,st.page*per+per);
  const n=k=>live.filter(so=>so.type===k).length;
  return head+`<div class="kpis">${tile('Running now',num(live.length),{icon:'repeat',note:[[n('Subscription'),'subscription'],[n('Wholesale'),'wholesale account'],[n('Regular'),'regular']].filter(x=>x[0]).map(([c,w])=>plural(c,w)).join(' · ')||'None running',i:0})}${tile('Pieces a week',num(Math.round(pieces)),{icon:'oven',note:'Averaged over every-2-week repeats',i:1})}${tile('Steady sales a week',money(weekly),{icon:'up',tone:'pos',note:`About ${money(weekly*52/12)} a month, before one-off orders`,count:weekly,i:2})}${tile('Next drop',next?esc(next.customer):'—',{icon:'calendar',note:next?`${longDay(next.dueDate)} ${date(next.dueDate)}`:'Nothing in the next four weeks',i:3})}</div>
  <section class="card table-card">${cardhead('Your standing orders',plural(all.length,'standing order'),'repeat')}<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Schedule</th><th>Each drop</th><th class="num">Per drop</th><th class="num">A week</th><th>Status</th><th></th></tr></thead><tbody>${all.map(so=>{const [s,c]=standingStatus(so);
   return `<tr${runningNow(so)?'':' class="dim"'}><td><strong>${esc(so.customer)}</strong><small class="dim" style="display:block">${esc(so.code)} · ${so.type}${so.prepaid?' · paid in advance':''}</small></td><td data-v="${so.days[0]}">${scheduleText(so)}<small class="dim" style="display:block">Bake ${leadText(so.bakeLead)}${so.end?` · until ${date(so.end)}`:''}</small></td><td><span class="clamp">${so.lines.map(l=>`${num(l.qty)} × ${esc(recipe(l.recipeId)?.name||'')}`).join('<br>')}</span></td><td class="num">${money(perDrop(so))}</td><td class="num">${money(perWeek(so,l=>l.qty*l.unitPrice))}</td><td data-v="${s}">${pill(s,c)}</td><td class="num">${button('Open','standing-form','small',`data-id="${esc(so.id)}"`)}</td></tr>`;}).join('')}</tbody></table></div></section>
  <section class="card table-card">${cardhead('The next four weeks','Drops already in your order book. Skip a week here: the drop is canceled and the plan updates.','calendar')}
   ${drops.length?`<div class="table-wrap"><table><thead><tr><th>Drop</th><th>Customer</th><th>Products</th><th class="num">Value</th><th>Status</th><th></th></tr></thead><tbody>${view.map(o=>`<tr${o.status==='Cancelled'?' class="dim"':''}><td data-v="${o.dueDate}" style="white-space:nowrap"><strong>${dayname(o.dueDate)} ${date(o.dueDate)}</strong><small class="dim" style="display:block">Bake ${date(o.bakeDate)}</small></td><td>${esc(o.customer)}<small class="dim" style="display:block">${esc(o.reference)}</small></td><td><span class="clamp">${o.lines.map(l=>`${num(l.qty)} × ${esc(recipe(l.recipeId)?.name||'')}`).join('<br>')}</span></td><td class="num">${money(rev(o))}</td><td data-v="${o.status}">${o.status==='Cancelled'?pill('Skipped',''):statusPill(o.status)}</td><td class="num" style="white-space:nowrap">${o.status==='Cancelled'?button('Bake it after all','drop-restore','small',`data-id="${esc(o.id)}"`):o.status==='Confirmed'&&!hasMade(o)?button('Skip this one','drop-skip','small quiet',`data-id="${esc(o.id)}"`):''}${button('Open','order-form','small',`data-id="${esc(o.id)}"`)}</td></tr>`).join('')}</tbody></table></div>${pager(st,drops.length,per)}`
   :empty('No drops in the next four weeks','Paused, ended, or starting later. Open a standing order to change its dates.','','calendar')}</section>
  <div class="notice"><span>Changing a standing order rebuilds its upcoming drops that haven’t started yet. Drops with batches made, a payment recorded or a status change stay as they are.</span></div>`;},

 markets(){const y=week.slice(0,4),all=state.orders.filter(isMarket),st=UI.markets,t=today();
  const head=pagehead(y,'Market days','Bake for stock, then count what came home. Sell-through and leftovers tell you how much to bring next time.',button('‹ '+(y-1),'year-shift','quiet','data-d="-1"')+button((+y+1)+' ›','year-shift','quiet','data-d="1"')+button(ico('plus')+'<span>Plan a market day</span>','market-form','primary'));
  if(!all.length)return head+`<section class="card">${empty('Plan your first market day','Choose what to bring and the pieces go into your bake plan, shopping list and batch sheets. Afterward, record what sold and where the leftovers went.',button('Plan a market day','market-form','primary'),'tent')}</section>`;
  const open=all.filter(o=>['Confirmed','Ready'].includes(o.status)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const done=all.filter(o=>o.status==='Collected'&&o.dueDate.startsWith(y)).sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).map(o=>({o,r:C.marketResult(state,o)}));
  const T=done.reduce((a,{r})=>({takings:a.takings+r.takings,brought:a.brought+r.brought,sold:a.sold+r.sold,kept:a.kept===null||r.kept===null?null:a.kept+r.kept,stall:a.stall+r.stallFee,lost:a.lost===null||r.lostValue===null?null:a.lost+r.lostValue,fate:Object.fromEntries(Object.keys(a.fate).map(k=>[k,a.fate[k]+r.byFate[k]]))}),{takings:0,brought:0,sold:0,kept:0,stall:0,lost:0,fate:{wasted:0,donated:0,kept:0,discounted:0}});
  const st8=done.slice(0,8).reverse().map(x=>x.r.sellThrough),left=T.brought-T.sold;
  const openCard=o=>{const m=o.status;return `<article class="order market"><div class="order-head"><div><div class="eyebrow">${longDay(o.dueDate)} ${date(o.dueDate)} · bake ${dayname(o.bakeDate)}</div><h3>${esc(o.customer)}</h3></div>${marketPill(m)}</div>
   ${o.lines.map(l=>`<div class="row"><span>${esc(recipe(l.recipeId)?.name||'Product')}</span><strong class="number">× ${num(l.qty)}</strong></div>`).join('')}
   <div class="row total"><span>At full price</span><strong>${money(rev(o))}</strong></div>${o.market.stallFee?`<p class="note">Stall fee ${money(o.market.stallFee)}</p>`:''}
   <div class="actions">${button('Edit','market-form','small quiet',`data-id="${esc(o.id)}"`)}${m==='Confirmed'&&!allMade(o)?button('Batch sheets','market-week','small quiet',`data-date="${o.bakeDate}"`):''}${m==='Confirmed'&&allMade(o)?button('Mark packed','order-status','small',`data-id="${esc(o.id)}" data-status="Ready"`):''}${o.dueDate<=t||m==='Ready'?button(ico('check')+'Record what sold','market-close','small primary',`data-id="${esc(o.id)}"`):''}</div></article>`;};
  // products across this year's closed market days
  const prod=new Map();for(const {o,r} of done)for(const l of r.lines){const k=l.recipeId,p=prod.get(k)||{brought:0,sold:0,days:0,lost:0};p.brought+=l.brought;p.sold+=l.sold;p.days++;if(['wasted','donated'].includes(l.fate)&&r.pieceCost!==null)p.lost+=l.leftover*r.pieceCost;prod.set(k,p);}
  const prows=[...prod].map(([id,p])=>({id,name:recipe(id)?.name||'Product',...p})).sort((a,b)=>b.sold-a.sold),top=prows.slice(0,6);
  const lastName=(done[0]||{o:open[0]}).o?.customer||'';
  const per=12,pages=Math.max(1,Math.ceil(done.length/per));st.page=Math.max(0,Math.min(st.page,pages-1));const view=done.slice(st.page*per,st.page*per+per);
  const fateRow=r=>Object.entries(r.byFate).filter(([,n])=>n).map(([k,n])=>`${num(n)} ${FATES[k].toLowerCase()}`).join(' · ')||'Sold out';
  return head+(done.length?`<section class="hero"><div><div class="eyebrow">Market takings · ${y}</div><div class="hero-num" data-count="${T.takings}">${money(T.takings)}</div>
   <p>From <b>${plural(done.length,'market day')}</b>. You sold <b>${pc(T.sold/T.brought)}</b> of what you brought; <b>${num(left)} pieces</b> came home${T.fate.wasted?`, and <b>${num(T.fate.wasted)}</b> of them were wasted`:''}.</p>
   <div class="actions">${button('Plan the next one','market-form','pop')}${open.length?button('Record what sold','market-close','ghost',`data-id="${esc(open[0].id)}"`):''}</div></div>
   <div class="hero-side"><div class="hero-fact">Average takings a day<strong>${money(T.takings/done.length)}</strong></div><div class="hero-fact">Kept after ingredients, packaging &amp; stall fees<strong>${cash(T.kept)}</strong></div>
   <div class="hero-meter" title="${pc(T.sold/T.brought)} sold"><i style="width:${(T.sold/T.brought*100).toFixed(1)}%"></i></div><div class="hero-fact">Sell-through<strong>${pc(T.sold/T.brought)}</strong></div><div class="hero-fact">Stall fees<strong>${money(T.stall)}</strong></div></div></section>`:'')+
  `<div class="kpis">${tile('Coming up',num(open.length),{icon:'tent',note:open[0]?`Next: ${esc(open[0].customer)}, ${date(open[0].dueDate)}`:'Nothing planned yet',go:'',i:0})}${tile('Sell-through',done.length?pc(T.sold/T.brought):'—',{icon:'insights',tone:'pos',note:done.length?`Last ${plural(st8.length,'market day')}`:'Close a market day to see it',sp:st8.length>1?spark(st8,trendColor(st8)):'',i:1})}${tile('Leftovers',num(left),{icon:'box',note:done.length?`${num(T.fate.donated)} given away · ${num(T.fate.kept)} kept · ${num(T.fate.discounted)} sold reduced`:'Pieces that came home',i:2})}${tile('Wasted, at cost',cash(T.lost),{icon:'trash',tone:'neg',note:`${num(T.fate.wasted+T.fate.donated)} pieces wasted or given away`,i:3})}</div>`+
  (open.length?`<section class="card">${cardhead('Coming up','Bring these, then record what sold when you’re home.','tent')}<div class="orders-grid">${open.map(openCard).join('')}</div></section>`:'')+
  (done.length?`<div class="grid2"><section class="card">${cardhead('Sold and left over','Pieces by product, every market day this year','insights')}${bars([{name:'Sold',color:'var(--ok)',values:top.map(p=>p.sold)},{name:'Left over',color:'var(--over)',values:top.map(p=>p.brought-p.sold)}],top.map(p=>p.name.length>13?p.name.slice(0,12).trim()+'…':p.name),{title:'Sold and left over by product',f:num,cf:v=>num(Math.round(v)),W:640,H:270})}</section>
   <section class="card">${cardhead('Where the leftovers went',`${num(left)} pieces this year`,'box')}${pie(Object.entries(T.fate).map(([k,n],i)=>[FATES[k],n,['var(--over)','var(--cat-3)','var(--cat-1)','var(--cat-2)'][i]]),{label:'Leftover pieces',center:num(left),sub:'PIECES',f:n=>plural(n,'piece')})||empty('Nothing came home','Every market day sold out. Bring a little more next time?','','check')}</section></div>
   <section class="card table-card">${cardhead('By product','What each product sells, and how many to bring next time','tags')}<div class="table-wrap"><table><thead><tr><th>Product</th><th class="num">Market days</th><th class="num">Brought</th><th class="num">Sold</th><th class="num">Sell-through</th><th class="num">Wasted, at cost</th><th class="num">Bring next time</th></tr></thead><tbody>${prows.map(p=>{const sg=C.marketSuggestion(state,lastName,p.id,'2199-12-31'),k=p.sold/p.brought;
    return `<tr><td><strong>${esc(p.name)}</strong></td><td class="num">${num(p.days)}</td><td class="num">${num(p.brought)}</td><td class="num">${num(p.sold)}</td><td class="num" data-v="${k}"><span class="pct"><i style="width:${(k*100).toFixed(0)}%"></i></span>${pc(k)}</td><td class="num" data-v="${p.lost}">${money(p.lost)}</td><td class="num" data-v="${sg?.suggest??-1}">${sg?`<strong>${num(sg.suggest)}</strong><small class="dim" style="display:block">${sg.soldOut?`sold out ${sg.soldOut} of ${sg.markets}`:`sells ~${num(Math.round(sg.avgSold))}`}</small>`:'—'}</td></tr>`;}).join('')}</tbody></table></div><p class="small dim" style="margin:10px 0 0">“Bring next time” uses the last four ${esc(lastName)} days: the average sold, or a little more than you brought when it keeps selling out.</p></section>
   <section class="card table-card">${cardhead('Market days this year',plural(done.length,'closed market day'),'log')}<div class="table-wrap"><table><thead><tr><th>Day</th><th class="num">Brought</th><th class="num">Sold</th><th class="num">Sell-through</th><th>Leftovers</th><th class="num">Takings</th><th class="num">Kept</th><th></th></tr></thead><tbody>${view.map(({o,r})=>`<tr><td data-v="${o.dueDate}"><strong>${date(o.dueDate)}</strong><small class="dim" style="display:block">${esc(o.customer)}</small></td><td class="num">${num(r.brought)}</td><td class="num">${num(r.sold)}</td><td class="num" data-v="${r.sellThrough}"><span class="pct"><i style="width:${(r.sellThrough*100).toFixed(0)}%"></i></span>${pc(r.sellThrough)}</td><td data-v="${r.leftover}"><small>${fateRow(r)}</small></td><td class="num">${money(r.takings)}</td><td class="num" data-v="${r.kept??-1e9}">${cash(r.kept)}</td><td class="num">${button('Open','market-close','small',`data-id="${esc(o.id)}"`)}</td></tr>`).join('')}</tbody></table></div>${pager(st,done.length,per)}</section>`
  :`<section class="card">${empty(`No closed market days in ${y}`,'After a market, choose Record what sold. Sell-through, leftovers and suggested amounts build up from there.','','insights')}</section>`);},
});
const FATES={wasted:'Wasted',donated:'Given away',kept:'Kept or frozen',discounted:'Sold reduced'};

/* ---------- dialogs ---------- */
function standingForm(id){if(!state.recipes.some(r=>!r.archived)){toast('Save a recipe first, so drops use your real costs.');return recipeForm();}
 const r0=state.recipes.find(r=>!r.archived),so=state.standing.find(x=>x.id===id)||{customer:'',contact:'',type:'Subscription',lines:[{recipeId:r0.id,qty:1,unitPrice:r0.unitPrice,finishMinutes:r0.finishMinutes}],days:[4],every:1,start:today(),end:'',bakeLead:0,finishLead:0,payment:'Card',prepaid:false,paused:false,setupMinutes:5,kitchenNote:''};
 standingRows=clone(so.lines);const leads=[['0','Same day as the drop'],['1','The day before'],['2','2 days before'],['3','3 days before']];
 modal(id?`${esc(so.code)} · ${esc(so.customer)}`:'Set up a standing order',id?`${scheduleText(so)} · ${money(perDrop(so))} a drop`:'Every drop joins your order book four weeks ahead and bakes, shops and packs like any order.',
 `<form id="standing-form" data-id="${esc(id||'')}"><div class="fields">${fld('customer','Customer or account',so.customer,{attrs:'required maxlength="150" placeholder="e.g. Corner Café or Bread club: Sam"'})}${sel('type','Kind',[['Subscription','Subscription (bread club, box)'],['Wholesale','Wholesale (café, shop, deli)'],['Regular','Regular customer']],so.type)}
  ${fld('contact','Contact or drop-off details',so.contact,{attrs:'maxlength="250"',full:true})}</div>
  <div class="form-section"><h3>Each drop</h3><div id="standing-rows">${lineRows(standingRows,'standing')}</div>${button(ico('plus')+'Add product','add-line','small quiet','data-scope="standing"')}</div>
  <div class="form-section"><h3>When</h3><div class="day-picks" role="group" aria-label="Drop days">${DAYS.map((d,i)=>`<label class="day-pick"><input type="checkbox" name="days" value="${i}" ${so.days.includes(i)?'checked':''}><span>${d}</span></label>`).join('')}</div>
   <div class="fields" style="margin-top:14px">${sel('every','Repeat',[['1','Every week'],['2','Every 2 weeks'],['3','Every 3 weeks'],['4','Every 4 weeks']],String(so.every))}${fld('start','First drop on or after',so.start,{type:'date',attrs:'required',hint:'Every 2–4 weeks counts from this week.'})}
   ${fld('end','Last drop',so.end,{type:'date',hint:'Optional. Leave empty to keep it going.'})}${fld('setupMinutes','Packing minutes per drop',so.setupMinutes,{type:'number',attrs:'min="0" step="any" required'})}
   ${sel('bakeLead','Bake',leads,String(so.bakeLead))}${sel('finishLead','Finish & pack',leads,String(so.finishLead))}</div></div>
  <div class="form-section"><h3>Payment</h3><div class="fields">${sel('payment','Payment method',[['Card','Card'],['Cash','Cash'],['Other','Other (invoice, transfer)']],so.payment)}
   <label class="check"><input type="checkbox" name="prepaid" ${so.prepaid?'checked':''}><span>Paid in advance<small>Each drop is created already paid, as with a prepaid subscription.</small></span></label>
   ${id?`<label class="check"><input type="checkbox" name="paused" ${so.paused?'checked':''}><span>Paused<small>No new drops until you switch this off. Upcoming drops that haven’t started are removed.</small></span></label>`:''}
   ${area('kitchenNote','Kitchen note on every drop',so.kitchenNote,'Only on kitchen paperwork.')}</div></div>
  <div class="formfoot">${id?button('Delete','standing-delete','danger quiet',`data-id="${esc(id)}"`):''}<button type="button" class="btn" data-action="dismiss">Cancel</button><button class="btn primary" type="submit">${id?'Save standing order':'Start standing order'}</button></div></form>`,true);}

const marketRef=d=>{const refs=new Set(state.orders.map(o=>o.reference.toLowerCase())),b='MK-'+d.slice(2).replace(/-/g,'');let r=b,k=2;while(refs.has(r.toLowerCase()))r=b+'-'+(k++);return r;};
function marketForm(id){const o=id?order(id):null;if(!o&&!state.recipes.some(r=>!r.archived)){toast('Save a recipe first, so market days use your real costs.');return recipeForm();}
 const ms=state.orders.filter(isMarket).sort((a,b)=>b.dueDate.localeCompare(a.dueDate)),last=ms[0],names=[...new Set(ms.map(x=>x.customer))];
 let d=C.addDays(week,5);if(d<today())d=C.addDays(C.monday(today()),d<C.addDays(C.monday(today()),5)?5:12);
 const r0=state.recipes.find(r=>!r.archived),m=o||{customer:last?.customer||'Farmers market',dueDate:d,bakeDate:C.addDays(d,-1),finishDate:d,setupMinutes:30,kitchenNote:'',market:{stallFee:last?.market.stallFee??0},
  lines:last?last.lines.filter(l=>!recipe(l.recipeId)?.archived).map(l=>({...l,unitPrice:recipe(l.recipeId).unitPrice})):[{recipeId:r0.id,qty:24,unitPrice:r0.unitPrice,finishMinutes:r0.finishMinutes}]};
 if(!m.lines.length)m.lines=[{recipeId:r0.id,qty:24,unitPrice:r0.unitPrice,finishMinutes:r0.finishMinutes}];
 marketRows=clone(m.lines);const locked=o&&hasMade(o),closed=o?.status==='Collected';
 modal(o?`${esc(o.customer)} · ${date(o.dueDate)}`:'Plan a market day',o?`${longDay(o.dueDate)} · ${num(o.lines.reduce((n,l)=>n+l.qty,0))} pieces · ${money(rev(o))} at full price`:'You bake for stock here: the pieces you bring go into the week’s plan, shopping list and batch sheets.',
 `${o?`<div class="actions" style="margin-bottom:8px">${marketPill(o.status)}${o.status==='Confirmed'&&allMade(o)?button('Mark packed','order-status','small',`data-id="${esc(id)}" data-status="Ready"`):''}${o.status!=='Cancelled'?button(closed?'Edit what sold':'Record what sold','market-close','small primary',`data-id="${esc(id)}"`):''}${['Ready','Collected','Cancelled'].includes(o.status)?button(o.status==='Cancelled'?'Plan it again':'Reopen','order-status','small quiet',`data-id="${esc(id)}" data-status="Confirmed"`):''}</div>`:''}
 ${closed?'<div class="notice"><span>This market day is closed. Reopen it to change what you brought.</span></div>':locked?'<div class="notice"><span>Batches for this market day are marked made. Undo them before changing products or dates.</span></div>':''}
 <form id="market-form" data-id="${esc(id||'')}"><fieldset ${locked||closed?'disabled':''} style="border:0;padding:0;margin:12px 0 0"><div class="fields">${fld('customer','Market name',m.customer,{attrs:'required maxlength="150" list="market-names"'})}<datalist id="market-names">${names.map(n=>`<option value="${esc(n)}">`).join('')}</datalist>${moneyFld('stallFee','Stall or pitch fee',m.market.stallFee)}
  ${fld('dueDate','Market day',m.dueDate,{type:'date',attrs:'required'})}${fld('bakeDate','Bake date',m.bakeDate,{type:'date',attrs:'required'})}${fld('finishDate','Pack date',m.finishDate,{type:'date',attrs:'required'})}${fld('setupMinutes','Packing & setup minutes',m.setupMinutes,{type:'number',attrs:'min="0" step="any" required'})}</div>
  <div class="form-section"><h3>What to bring</h3><div id="market-rows">${lineRows(marketRows,'market')}</div><div class="actions">${button(ico('plus')+'Add product','add-line','small quiet','data-scope="market"')}${button(ico('spark')+'Use suggested amounts','market-suggest','small')}</div><div id="market-hints" class="market-hints"></div></div>
  <div class="fields">${area('kitchenNote','Kitchen note',m.kitchenNote,'Float, signage, what to load first…')}</div></fieldset>
  <div class="formfoot">${o&&!locked&&!closed&&o.status!=='Cancelled'?button('Market canceled','cancel-order','danger',`data-id="${esc(id)}"`):''}${o&&!locked?button('Delete','delete-order','danger quiet',`data-id="${esc(id)}"`):''}<button type="button" class="btn" data-action="dismiss">Close</button>${!locked&&!closed?`<button class="btn primary" type="submit">${o?'Save market day':'Add to the plan'}</button>`:''}</div></form>`,true);marketHints();}
function marketHints(){const box=$('#market-hints');if(!box)return;const f=$('#market-form'),name=f.customer.value.trim(),d=f.dueDate.value||today();
 const rows=marketRows.map(l=>({l,s:/^\d{4}-\d{2}-\d{2}$/.test(d)?C.marketSuggestion(state,name,l.recipeId,d):null}));
 box.innerHTML=rows.some(r=>r.s)?`<div class="section-label">From your last ${esc(name)} days</div>`+rows.map(({l,s})=>`<div class="row"><div><strong>${esc(recipe(l.recipeId)?.name||'')}</strong><small>${s?`Sold ${num(Math.round(s.avgSold))} of ${num(Math.round(s.avgBrought))} on average${s.soldOut?` · sold out ${s.soldOut} of ${s.markets}`:''}`:'No history for this product yet'}</small></div><strong class="number">${s?(s.suggest===l.qty?pill('Bring '+num(s.suggest),'good'):'Bring '+num(s.suggest)):'—'}</strong></div>`).join('')
  :`<p class="small dim">After you record what sold at ${name?esc(name):'a market'} a few times, suggested amounts appear here.</p>`;}
function closeForm(id){const o=order(id),res=rid=>o.market.results.find(r=>r.recipeId===rid),ready=o.status!=='Confirmed'||allMade(o);
 modal(`What sold at ${esc(o.customer)}?`,`${longDay(o.dueDate)} ${date(o.dueDate)} · count what came home and the rest is worked out for you.`,
 `${ready?'':`<div class="notice warning"><span><b>Mark this market day’s batches made first.</b> Then leftovers are counted against what you actually baked.</span>${button('Batch sheets','market-week','small',`data-date="${o.bakeDate}"`)}</div>`}
 <form id="close-form" data-id="${esc(id)}"><div class="table-wrap"><table data-nosort class="close-table"><thead><tr><th>Product</th><th class="num">Brought</th><th class="num">Sold</th><th class="num">Left</th><th>Leftovers went to</th><th class="num">Reduced takings</th></tr></thead><tbody>
 ${o.lines.map((l,i)=>{const r=res(l.recipeId),nm=esc(recipe(l.recipeId)?.name||'Product');return `<tr><td><strong>${nm}</strong><small class="dim" style="display:block">${money(l.unitPrice)} each</small></td><td class="num">${num(l.qty)}</td><td class="num"><input class="num-in" name="sold${i}" type="number" min="0" max="${l.qty}" step="1" value="${r?r.sold:l.qty}" required aria-label="${nm}: pieces sold"></td><td class="num" data-left="${i}"></td>
  <td><select name="fate${i}" aria-label="${nm}: where the leftovers went">${Object.entries(FATES).map(([k,v])=>`<option value="${k}" ${(r?.fate||'wasted')===k?'selected':''}>${v}</option>`).join('')}</select></td><td class="num"><input class="num-in" name="reduced${i}" type="number" min="0" step="0.01" value="${r?.reducedTakings||0}" aria-label="${nm}: takings from reduced sales"></td></tr>`;}).join('')}</tbody></table></div>
 <div class="close-sum" id="close-sum"></div>
 <div class="formfoot">${button('Everything sold','close-all','quiet')}<button type="button" class="btn" data-action="dismiss">Cancel</button><button class="btn primary" type="submit" ${ready?'':'disabled'}>${o.status==='Collected'?'Save':'Close market day'}</button></div></form>`,true);closeSum();}
function closeSum(){const f=$('#close-form');if(!f)return;const o=order(f.dataset.id);let sold=0,brought=0,tk=0;
 o.lines.forEach((l,i)=>{const s=Math.max(0,Math.min(l.qty,Math.round(+f[`sold${i}`].value||0))),left=l.qty-s,fate=f[`fate${i}`].value;sold+=s;brought+=l.qty;tk+=s*l.unitPrice+(left&&fate==='discounted'?+f[`reduced${i}`].value||0:0);
  f.querySelector(`[data-left="${i}"]`).textContent=num(left);f[`fate${i}`].disabled=!left;f[`reduced${i}`].disabled=!left||fate!=='discounted';});
 $('#close-sum').innerHTML=`<div class="row"><span>Takings</span><strong class="number">${money(tk)}</strong></div><div class="row"><span>Sold</span><strong class="number">${num(sold)} of ${num(brought)} · ${pc(brought?sold/brought:NaN)}</strong></div><div class="row"><span>Came home</span><strong class="number">${plural(brought-sold,'piece')}</strong></div>`;}

/* ---------- actions and form events ---------- */
Object.assign(ACTIONS,{
 'standing-form':b=>standingForm(b.dataset.id),'market-form':b=>marketForm(b.dataset.id),'market-close':b=>closeForm(b.dataset.id),
 'market-week':b=>{closeModal();week=C.monday(b.dataset.date);selectedDay='';go('batches');},
 'standing-delete':b=>{const so=state.standing.find(x=>x.id===b.dataset.id);ask(`Delete ${esc(so.customer)}’s standing order?`,'Upcoming drops that haven’t started are removed. Past drops stay in your order book. You can undo straight after.','Delete standing order',()=>commit(s=>C.deleteStanding(s,so.id,today()),'Standing order deleted'));},
 'drop-skip':b=>commit(s=>C.setOrderStatus(s,b.dataset.id,'Cancelled'),'Skipped. It’s out of the plan and shopping list.'),
 'drop-restore':b=>commit(s=>C.setOrderStatus(s,b.dataset.id,'Confirmed'),'Back in the plan'),
 'market-suggest':()=>{const f=$('#market-form');let n=0;for(const l of marketRows){const s=C.marketSuggestion(state,f.customer.value.trim(),l.recipeId,f.dueDate.value||today());if(s){l.qty=s.suggest;n++;}}if(!n)return formError('No history yet for these products at this market. Record what sold after a market day first.');redrawRows('market');},
 'close-all':()=>{const f=$('#close-form'),o=order(f.dataset.id);o.lines.forEach((l,i)=>f[`sold${i}`].value=l.qty);closeSum();},
});
document.addEventListener('input',e=>{const x=e.target;if(x.closest?.('#close-form'))closeSum();if(x.closest?.('#market-form')&&['customer','dueDate'].includes(x.name))marketHints();});
document.addEventListener('change',e=>{const x=e.target;if(x.closest?.('#close-form'))closeSum();
 if(x.form?.id==='market-form'&&x.name==='dueDate'&&/^\d{4}-\d{2}-\d{2}$/.test(x.value)){const f=x.form;if(!f.dataset.id){f.bakeDate.value=C.addDays(x.value,-1);f.finishDate.value=x.value;}marketHints();}});
document.addEventListener('submit',e=>{const f=e.target,id=f.dataset.id;
 if(f.id==='standing-form'){const days=new FormData(f).getAll('days');if(!days.length)return formError('Choose at least one day of the week.');
  formSave(f,(s,d)=>C.saveStanding(s,{...d,id:id||undefined,days,lines:standingRows,prepaid:f.prepaid.checked,paused:!!f.paused?.checked},today()),id?'Standing order saved. Upcoming drops updated.':'Standing order started. Its drops are in your order book.');}
 if(f.id==='market-form')formSave(f,(s,d)=>{const data={customer:d.customer,dueDate:d.dueDate,bakeDate:d.bakeDate,finishDate:d.finishDate,setupMinutes:d.setupMinutes,kitchenNote:d.kitchenNote,lines:marketRows,market:{stallFee:d.stallFee===''?0:d.stallFee}};
  return id?C.updateOrder(s,id,data):C.addOrder(s,{...data,kind:'market',reference:marketRef(d.dueDate),contact:'',payment:'Cash',paid:0,extraCost:0,customerNote:''});},id?'Market day saved':'Market day added. Its batches and shopping are in the week plan.');
 if(f.id==='close-form'){if(!f.reportValidity())return;const o=order(id),results=o.lines.map((l,i)=>({recipeId:l.recipeId,sold:+f[`sold${i}`].value,fate:f[`fate${i}`].value,reducedTakings:f[`fate${i}`].value==='discounted'?+f[`reduced${i}`].value||0:0}));
  try{apply(s=>{if(s.orders.find(x=>x.id===id).status==='Confirmed')C.setOrderStatus(s,id,'Ready');C.closeMarket(s,id,results);});closeModal();render();toast('Market day closed. Sell-through and leftovers updated.',true);}catch(err){formError(err.message);}}});
