/* ================================================================================
   Bakeweek Studio · UI, part 2: screens, dialogs, kitchen paperwork, events.
   ================================================================================ */
const UI={orders:{q:'',page:0,status:'open'},recipes:{q:'',cat:'all',status:'active',sort:'category'},pantry:{q:'',page:0}};
let recipeRows=[],orderRows=[],simDraft=null,simResult=null,importPreview=null;
const rev=o=>o.lines.reduce((n,l)=>n+l.qty*l.unitPrice,0);
const balance=o=>Math.max(0,rev(o)-o.paid);
const plan=()=>C.planWeek(state,week);
// the last eight weeks up to the week on screen: quoted sales and hands-on minutes, for the sparklines
let seriesMemo={};
function weekSeries(n=8){const k=week+'|'+n;if(seriesMemo.s===state&&seriesMemo.k===k)return seriesMemo.v;
 const v=Array.from({length:n},(_,i)=>{const p=C.planWeek(state,C.addDays(week,-7*(n-1-i)));return {sales:p.totals.quotedRevenue,minutes:p.totals.activeMinutes};});seriesMemo={s:state,k,v};return v;}
function recipeCostPerPiece(r){let c=0;for(const x of r.ingredients){const i=ingredient(x.ingredientId);if(!i||i.packCost===null)return null;c+=x.qty*i.packCost/i.packSize;}return c/r.yield+r.packagingCost;}
const wkEyebrow=()=>`Week of ${weekLabel(week)}`;

/* ---------- the sample bakery: Sunday Crumb's current week (BakeCore's demo) plus ~40 weeks of collected orders ----------
   Past orders are planned with C.planWeek, recorded as made batches, then collected and paid, so the whole
   history passes C.validateBackup like real data. Pantry stock stays at the demo's values. */
function sampleBakery(){const s=C.createDemo(today()),start=C.monday(today());let seed=19;const rnd=()=>(seed=(seed*16807)%2147483647)/2147483647,pick=a=>a[Math.floor(rnd()*a.length)];
 const names=['Harper','Mateo','Priya','Jonah','Lucia','Amara','Felix','Sofia','Kai','Nadia','Owen','Ruby','Elias','Mina','Theo','Clara','Jude','Ivy','Rafael','Hazel','Omar','Greta','Luca','Sana'].map((n,i)=>n+' '+'ABCDEFGHJKLMNPRSTW'[i%18]+'.');
 const recipes=s.recipes.map(r=>r.id),hist=[],weeks=[];let n=0;
 for(let w=40;w>=1;w--){const wk=C.addDays(start,-7*w),m=+wk.slice(5,7),busy=[11,12].includes(m)?3:[2,5,10].includes(m)?2:[7,8].includes(m)?0:1,count=1+busy+Math.floor(rnd()*2);weeks.push(wk);
  for(let k=0;k<count;k++){const rid=pick(recipes),r=s.recipes.find(x=>x.id===rid),due=C.addDays(wk,2+Math.floor(rnd()*4)),lines=[{recipeId:r.id,qty:pick([12,24,24,36,48]),unitPrice:r.unitPrice,finishMinutes:r.finishMinutes}];
   if(rnd()<.25){const id2=pick(recipes),r2=id2!==r.id&&s.recipes.find(x=>x.id===id2);if(r2)lines.push({recipeId:r2.id,qty:pick([12,24]),unitPrice:r2.unitPrice,finishMinutes:r2.finishMinutes});}
   const o={id:'sample-past-'+(++n),reference:'SC-'+String(n).padStart(4,'0'),customer:pick(names),contact:'',dueDate:due,bakeDate:C.addDays(due,-1),finishDate:due,status:rnd()<.06?'Cancelled':'Confirmed',paid:0,payment:pick(['Card','Card','Cash','Other']),setupMinutes:10,extraCost:0,customerNote:'',kitchenNote:'Made-up sample order.',lines,snapshot:null};
   s.orders.push(o);if(o.status==='Confirmed')hist.push(o);}}
 let runs=0;for(const wk of weeks)for(const run of C.planWeek(s,wk).runs){const rec={...run,id:'sample-run-'+(++runs),createdAt:run.date+'T18:00:00.000Z'};delete rec.yield;s.completedRuns.push(rec);}
 for(const o of hist){o.status='Collected';o.snapshot=C.quoteOrder(s,o);o.paid=o.snapshot.revenue;}
 return C.validateBackup(s);}

/* ---------- recipe categories (ordered list in prefs, plus any in use) and pictures ---------- */
const catList=()=>{const l=[...prefs.categories];for(const r of state.recipes)if(r.category&&!l.includes(r.category))l.push(r.category);return l;};
// each category has a color: the one the baker picked, else the next one in this palette by position
const CAT_PALETTE=['#c0573e','#d9902b','#5b8c3a','#2f7f8f','#4e6bb8','#8a55a8','#c4497a','#7a6a52'];
const catColor=c=>{if(!c)return '#8a8f98';const k=catList().indexOf(c);return prefs.categoryColors[c]||CAT_PALETTE[(k<0?0:k)%CAT_PALETTE.length];};
const catChip=c=>`<span class="cat-chip" style="--cc:${catColor(c)}">${esc(c||'Uncategorized')}</span>`;
let recipeImg;   // undefined = unchanged, null = remove, string = new picture for the recipe being edited
function readPicture(file){return new Promise((res,rej)=>{if(!file||!/^image\//.test(file.type))return rej(Error('Choose an image file.'));const url=URL.createObjectURL(file),img=new Image();
 img.onload=()=>{const W=640,H=480,c=document.createElement('canvas');c.width=W;c.height=H;const k=Math.max(W/img.width,H/img.height),w=img.width*k,h=img.height*k;c.getContext('2d').drawImage(img,(W-w)/2,(H-h)/2,w,h);URL.revokeObjectURL(url);
  let d=c.toDataURL('image/jpeg',.8);if(d.length>300000)d=c.toDataURL('image/jpeg',.6);d.length>390000?rej(Error('That picture is too large.')):res(d);};
 img.onerror=()=>{URL.revokeObjectURL(url);rej(Error('That picture couldn’t be read.'));};img.src=url;});}
const imgBox=(src,color)=>`<div class="recipe-img" style="--rc:${esc(color)}">${src?`<img src="${src}" alt="">`:'<span>No picture yet</span>'}</div>`;

/* ---------- small form helpers ---------- */
const fld=(name,label,value,{type='text',attrs='',hint='',full=false}={})=>`<label class="${full?'full':''}">${label}<input name="${name}" type="${type}" value="${esc(value??'')}" ${attrs}>${hint?`<small>${hint}</small>`:''}</label>`;
const moneyFld=(name,label,value,hint='',full=false)=>fld(name,label,value,{type:'number',attrs:'min="0" max="100000000" step="0.01" inputmode="decimal"',hint,full});
const sel=(name,label,options,value,{full=false,attrs=''}={})=>`<label class="${full?'full':''}">${label}<select name="${name}" ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
const area=(name,label,value,hint='')=>`<label class="full">${label}<textarea name="${name}" rows="3">${esc(value??'')}</textarea>${hint?`<small>${hint}</small>`:''}</label>`;

/* ---------- pieces shared by several screens ---------- */
function runCard(r,expanded=false){const rec=recipe(r.recipeId),made=!!r.id,y=r.yield||Math.round(r.produced/r.batches);
 return `<article class="run" style="--rc:${esc(rec?.color||'#9A6B52')}"><div class="run-top"><span class="avatar">${esc(initial(r.recipeName))}</span><div><h3>${esc(r.recipeName)}</h3><p>${plural(r.batches,'batch','batches')} × ${num(y)} = <b>${num(r.produced)} made</b> · ${num(r.required)} ordered${r.extra?` · ${num(r.extra)} extra`:''}</p></div>${made?pill(ico('check')+'Made','good'):pill(mins(r.activeMinutes)+' hands-on','flag')}</div>
 <div class="run-meta"><span>${ico('calendar')}${dayname(r.date)} ${date(r.date)}</span><span>${ico('oven')}${mins(r.ovenMinutes)} oven</span><span>${ico('coins')}${cash(r.ingredientCost)} ingredients</span></div>
 ${expanded?`<div class="rows">${r.ingredients.map(i=>`<div class="row"><span>${esc(i.name)}</span><strong class="number">${qty(i.qty,i.unit)}</strong></div>`).join('')}</div>${rec?.method?`<p class="method">${esc(rec.method)}</p>`:''}<p class="alloc"><b>For:</b> ${r.allocations.map(a=>`${esc(order(a.orderId)?.customer||'Order')} ${num(a.qty)}`).join(' · ')}${r.extra?` · <span class="dim">${num(r.extra)} extra pieces aren’t assigned to an order</span>`:''}</p>`:''}
 <div class="actions">${!expanded?button('Batch sheet','go','small quiet','data-go="batches"'):''}${made?button('Undo batch','undo-run','small',`data-id="${esc(r.id)}"`):button(ico('check')+'Mark batch made','complete-run','small primary',`data-key="${esc(r.key)}"`)}</div></article>`;}
function orderCard(o){return `<article class="order"><div class="order-head"><div><div class="eyebrow">${esc(o.reference)} · pickup ${dayname(o.dueDate)} ${date(o.dueDate)}</div><h3>${esc(o.customer)}</h3></div>${statusPill(o.status)}</div>
 ${o.lines.map(l=>`<div class="row"><span>${esc(recipe(l.recipeId)?.name||'Product')}</span><strong class="number">× ${num(l.qty)}</strong></div>`).join('')}
 <div class="row total"><span>Balance due</span><strong>${money(balance(o))}</strong></div>${o.kitchenNote?`<p class="note">Kitchen: ${esc(o.kitchenNote)}</p>`:''}
 <div class="actions">${button('Payment','payment','small quiet',`data-id="${esc(o.id)}"`)}${button(ico('print')+'Quote','print','small quiet',`data-k="quote" data-id="${esc(o.id)}"`)}${o.status==='Confirmed'?button('Mark ready','order-status','small primary',`data-id="${esc(o.id)}" data-status="Ready"`):o.status==='Ready'?button('Mark collected','order-status','small primary',`data-id="${esc(o.id)}" data-status="Collected"`):''}</div></article>`;}
function firstSteps(){const a=state.ingredients.length,b=state.recipes.length;
 return `<section class="card">${empty('See the work behind an order','Explore Sunday Crumb, a made-up bakery, to see orders become batches, shopping and a realistic week. Then build your own library, one recipe at a time.',button('Explore the sample bakery','sample','primary')+' '+button('How it works','go','','data-go="guide"'),'oven')}</section>
 <div class="steps">${[['01 / PANTRY','Know your ingredients','Pack sizes, what they cost and what’s already on your shelves.',a?button('Open pantry','go','small','data-go="pantry"'):button('Add your first ingredient','ingredient-form','small')],
  ['02 / RECIPES','Save one repeatable recipe','Yield, ingredients and hands-on minutes. Use your own tested formula.',b?button('Open recipes','go','small','data-go="recipes"'):button('Add your first recipe','recipe-form','small')],
  ['03 / ORDERS','Try an order before saying yes','See the extra work and costs, then accept it when the plan works.',button('Try an order','simulator','small primary')]].map(([n,h,p,btn])=>`<div class="step"><span>${n}</span><h3>${h}</h3><p>${p}</p>${btn}</div>`).join('')}</div>`;}
function weekTips(p){const t=[],over=p.days.filter(d=>d.overMinutes>0),busy=p.days.reduce((b,d)=>d.activeMinutes>b.activeMinutes?d:b,p.days[0]);
 if(over.length)t.push(`<b>${plural(over.length,'day')} over your hours:</b>&nbsp;${over.map(d=>`${dayname(d.date)} +${mins(d.overMinutes)}`).join(' · ')}`);
 if(busy.activeMinutes)t.push(`<b>Busiest day: ${longDay(busy.date)}</b>&nbsp;· ${mins(busy.activeMinutes)} of ${mins(busy.capacity)} planned`);
 const next=p.orders.filter(o=>['Confirmed','Ready'].includes(o.status)&&o.dueDate>=today()).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];
 if(next)t.push(`<b>Next pickup:</b>&nbsp;${esc(next.customer)} · ${longDay(next.dueDate)} ${date(next.dueDate)}`);
 const short=p.shopping.filter(x=>x.shortfall>0);if(short.length)t.push(`<b>${plural(short.length,'ingredient')} to buy</b>&nbsp;· ${money(p.totals.shoppingCost)} in whole packs`);
 if(p.totals.balanceDue>0)t.push(`<b>${money(p.totals.balanceDue)} still to collect</b>&nbsp;from this week’s pickups`);
 if(p.totals.unknownCosts)t.push(`<b>${plural(p.totals.unknownCosts,'ingredient price')} missing</b>&nbsp;· cost estimates are incomplete`);
 if(p.totals.extra)t.push(`<b>${num(p.totals.extra)} extra pieces</b>&nbsp;from whole batches aren’t assigned to an order`);
 return t;}

/* ================================================================================
   Screens
   ================================================================================ */
const VIEWS={
 week(){const p=plan(),cap=p.days.reduce((n,d)=>n+d.capacity,0),over=p.days.filter(d=>d.overMinutes>0),used=cap?p.totals.activeMinutes/cap:NaN;
  const head=pagehead(wkEyebrow(),'This week','One set of orders. A plan for what to buy, bake and pack.',button(ico('clock')+'<span>Available hours</span>','capacity','quiet')+button(ico('print')+'<span>Kitchen packet</span>','print','','data-k="packet"')+button(ico('spark')+'<span>Try an order</span>','simulator','primary'));
  if(!state.recipes.length&&!state.orders.length)return head+firstSteps();
  if(!selectedDay||!p.days.some(d=>d.date===selectedDay))selectedDay=(over[0]||p.days.find(d=>d.activeMinutes>0)||p.days[0]).date;
  const d=p.days.find(x=>x.date===selectedDay),series=weekSeries(),short=p.shopping.filter(x=>x.shortfall>0).length,toHand=p.orders.filter(o=>o.status!=='Collected').length;
  return head+pulse(weekTips(p))+
  `<section class="hero"><div><div class="eyebrow">Hands-on work · ${weekLabel(week)}</div><div class="hero-num" data-count="${p.totals.activeMinutes}" data-fmt="mins">${mins(p.totals.activeMinutes)}</div>
   <p>${over.length?`<b>${longDay(over[0].date)} needs ${mins(over[0].overMinutes)} more than you have.</b> Review that day, or try a different production day before taking more orders.`:cap?`Of the <b>${mins(cap)}</b> you set aside this week: <b>${pc(used)}</b> planned and <b>${mins(Math.max(0,cap-p.totals.activeMinutes))}</b> still free, across ${plural(p.totals.orders,'pickup')}.`:'Set your available hours to see how full the week is.'}</p>
   <div class="actions">${button('Can I fit another order?','simulator','pop')}${over.length?button('Review '+dayname(over[0].date),'select-day','ghost',`data-date="${over[0].date}"`):button('Open batch sheets','go','ghost','data-go="batches"')}</div></div>
   <div class="hero-side"><div class="hero-fact">Quoted sales<strong>${money(p.totals.quotedRevenue)}</strong></div><div class="hero-fact">Balance to collect<strong>${money(p.totals.balanceDue)}</strong></div>
   <div class="hero-meter" title="${pc(used)} of your hours"><i style="width:${Math.max(0,Math.min(100,(used||0)*100)).toFixed(1)}%${over.length?';background:var(--over)':''}"></i></div>
   <div class="hero-fact">Time planned<strong>${pc(used)} of ${hrs(cap)}</strong></div><div class="hero-fact">Ingredients to buy<strong>${money(p.totals.shoppingCost)}</strong></div></div></section>`+
  `<div class="kpis">${tile('Batches to make',num(p.totals.pendingBatches),{note:`${plural(p.totals.completedBatches,'batch','batches')} already made`,icon:'oven',go:'batches',i:0})}${tile('Ingredients to buy',num(short),{note:`${money(p.totals.shoppingCost)} in planned packs`,tone:'neg',icon:'cart',go:'shopping',i:1})}${tile('Orders to hand over',num(toHand),{note:`${money(p.totals.balanceDue)} balance due`,tone:'pos',icon:'box',go:'packing',i:2})}${tile('Quoted sales',money(p.totals.quotedRevenue),{note:delta(series.at(-1).sales,series.at(-2).sales),tone:'pos',icon:'up',sp:series.filter(x=>x.sales>0).length>1?spark(series.map(x=>x.sales),trendColor(series.map(x=>x.sales))):'',count:p.totals.quotedRevenue,i:3})}</div>`+
  `<section class="card">${cardhead('Day by day','Hands-on time against the hours you set. Pick a day to see its kitchen plan.','calendar')}<div class="days">${p.days.map(x=>{const o=x.overMinutes>0,w=x.capacity?x.activeMinutes/x.capacity*100:x.activeMinutes?100:0;
   return `<button class="day ${o?'over':''}" data-action="select-day" data-date="${x.date}" aria-pressed="${x.date===selectedDay}"><small>${dayname(x.date)}</small><b>${+x.date.slice(8)}</b><div class="timebar"><i style="width:${Math.min(100,w).toFixed(0)}%"></i></div><em>${!x.capacity&&!x.activeMinutes?'No hours set':`${mins(x.activeMinutes)} / ${mins(x.capacity)}`}</em><strong${!x.capacity&&!x.activeMinutes?' class="dim"':''}>${o?mins(x.overMinutes)+' over':!x.capacity?'Day off':mins(Math.max(0,x.capacity-x.activeMinutes))+' free'}</strong></button>`;}).join('')}</div></section>`+
  `<div class="grid2"><section class="card">${cardhead(`${longDay(d.date)}’s kitchen plan`,`${date(d.date)} · ${mins(d.activeMinutes)} hands-on of ${mins(d.capacity)}`,'oven',pill(d.overMinutes?mins(d.overMinutes)+' over':mins(Math.max(0,d.capacity-d.activeMinutes))+' free',d.overMinutes?'warn':'good'))}
   ${d.runs.length?`<div class="runs">${d.runs.map(r=>runCard(r)).join('')}</div>`:''}
   ${d.orders.length?`<div class="section-label">Finish &amp; pack</div>${d.orders.map(o=>`<div class="order-line"><div><strong>${esc(o.customer)}</strong><small>${esc(o.reference)} · pickup ${date(o.dueDate)} · ${o.lines.map(l=>`${num(l.qty)} ${esc(recipe(l.recipeId)?.name||'')}`).join(' · ')}</small></div><div class="actions">${pill(mins(o.setupMinutes+o.lines.reduce((n,l)=>n+l.qty*l.finishMinutes,0)),'flag')}${button('Open','order-form','small',`data-id="${esc(o.id)}"`)}</div></div>`).join('')}`:''}
   ${!d.runs.length&&!d.orders.length?empty('A little space in the week','Nothing to bake or pack on this day. Try a proposed order to see what fits.',button('Try an order','simulator','primary'),'spark'):''}</section>
   <section class="card">${cardhead('Hands-on time by day','Baking prep and finishing, against the hours you set','clock')}${bars([{name:'Baking prep',color:'var(--cat-1)',values:p.days.map(x=>x.bakeMinutes)},{name:'Finishing & packing',color:'var(--cat-2)',values:p.days.map(x=>x.finishMinutes)}],p.days.map(x=>dayname(x.date)),{title:'Hands-on time by day',overlay:{name:'Hours you set',color:'var(--ink-3)',values:p.days.map(x=>x.capacity),dash:true},f:mins,cf:hrs,W:480,H:250})}
   <div class="row"><span>Oven time (reference, not scheduled)</span><strong class="number">${mins(p.totals.ovenMinutes)}</strong></div><div class="row"><span>Extra pieces from whole batches</span><strong class="number">${num(p.totals.extra)}</strong></div>
   ${p.totals.unknownCosts?`<div class="notice warning" style="margin:12px 0 0"><span><b>${plural(p.totals.unknownCosts,'ingredient price')} missing.</b> Cost estimates are incomplete until they’re in.</span>${button('Open pantry','go','small','data-go="pantry"')}</div>`:''}</section></div>`;},

 shopping(){const p=plan(),rows=p.shopping.filter(x=>x.required>0),short=rows.filter(x=>x.shortfall>0),req=p.runs.some(r=>r.ingredientCost===null)?null:p.runs.reduce((n,r)=>n+r.ingredientCost,0),missing=rows.filter(x=>ingredient(x.ingredientId)?.packCost===null).length;
  const bySupplier=new Map();short.forEach(x=>{if(x.cost)bySupplier.set(x.supplier||'No supplier entered',(bySupplier.get(x.supplier||'No supplier entered')||0)+x.cost);});
  return pagehead(wkEyebrow(),'Shopping','Shared ingredients totaled, pantry stock subtracted, pack sizes rounded up.',button(ico('down')+'<span>Shopping list</span>','shopping-text','quiet')+button(ico('print')+'<span>Print</span>','print','','data-k="shopping"')+button(ico('check')+'<span>Receive planned shopping</span>','receive-shopping','primary'))+
  `<div class="kpis">${tile('Recipe requirements',money(req),{note:'Ingredients for batches still to make',icon:'tags',i:0})}${tile('Cash needed for packs',money(p.totals.shoppingCost),{note:'After what’s already in your pantry',tone:'neg',icon:'cart',i:1})}${tile('Ingredients to buy',num(short.length),{note:`${num(rows.length-short.length)} already covered`,icon:'log',i:2})}${tile('Missing prices',num(missing),{note:missing?'Add them in Pantry for exact costs':'Every price is in',tone:missing?'neg':'pos',icon:'coins',go:missing?'pantry':'',i:3})}</div>
  <div class="grid2 wide-left"><section class="card table-card">${cardhead('The list, already combined',`${plural(short.length,'item')} to buy for ${weekLabel(week)}`,'cart')}
   ${rows.length?`<div class="table-wrap"><table><thead><tr><th>Ingredient</th><th class="num">Need</th><th class="num">In pantry</th><th class="num">Short</th><th>Buy</th><th class="num">Est. spend</th></tr></thead><tbody>${rows.map(i=>`<tr><td><strong>${esc(i.name)}</strong><small class="dim" style="display:block">${esc(i.supplier||'No supplier entered')}</small></td><td class="num" data-v="${i.required}">${qty(i.required,i.unit)}</td><td class="num" data-v="${i.stock}">${qty(i.stock,i.unit)}</td><td class="num" data-v="${i.shortfall}">${i.shortfall?qty(i.shortfall,i.unit):pill('Covered','good')}</td><td data-v="${i.packs}" style="white-space:nowrap">${i.packs?`<strong>${num(i.packs)} × ${qty(i.packSize,i.unit)}</strong>`:'—'}</td><td class="num" data-v="${i.cost??-1}">${i.packs?cash(i.cost):money(0)}</td></tr>`).join('')}<tr class="total"><td colspan="5">Planned purchase cost</td><td class="num">${cash(p.totals.shoppingCost)}</td></tr></tbody></table></div>`:empty('Nothing to buy for this week','Your batches may already be made, or no orders are baking this week.','','cart')}</section>
   <section class="card">${cardhead('Spend by supplier','Planned packs only','coins')}${pie(fold([...bySupplier]),{label:'Planned spend',center:compact(p.totals.shoppingCost||0),sub:'TO SPEND'})||empty('No purchases planned','Your pantry covers every batch this week.','','check')}
   <div class="notice" style="margin:16px 0 0"><span><b>Receive planned shopping</b> adds the listed packs to your pantry. Use it only once they’ve arrived; record partial or different purchases in Pantry.</span></div></section></div>`;},

 batches(){const p=plan(),pieces=p.runs.reduce((n,r)=>n+r.produced,0);
  return pagehead(wkEyebrow(),'Batch sheets','The same recipe on the same baking day becomes one production run, scaled to whole batches.',button(ico('print')+'<span>Print batch sheets</span>','print','','data-k="batches"'))+
  `<div class="kpis">${tile('Batches to make',num(p.totals.pendingBatches),{note:`${num(pieces)} pieces`,icon:'oven',i:0})}${tile('Hands-on baking',mins(p.runs.reduce((n,r)=>n+r.activeMinutes,0)),{note:'Mixing, portioning and prep',icon:'clock',i:1})}${tile('Oven time',mins(p.runs.reduce((n,r)=>n+r.ovenMinutes,0)),{note:'A reference, not an oven schedule',icon:'history',i:2})}${tile('Already made',num(p.totals.completedBatches),{note:'Ingredients already taken from the pantry',tone:'pos',icon:'check',i:3})}</div>
  <section class="card">${cardhead('To make',`${plural(p.runs.length,'production run')} · scaled ingredients, method and who each batch is for`,'oven')}${p.runs.length?`<div class="runs two">${p.runs.map(r=>runCard(r,true)).join('')}</div>`:empty('No batches waiting','Accept an order, or pick another week at the top.',button('Try an order','simulator','primary'),'oven')}</section>
  ${p.completedRuns.length?`<section class="card">${cardhead('Already made this week',plural(p.completedRuns.length,'production record'),'check')}<div class="runs two">${p.completedRuns.map(r=>runCard(r,true)).join('')}</div></section>`:''}`;},

 packing(){const p=plan(),os=p.orders.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.customer.localeCompare(b.customer));
  return pagehead(wkEyebrow(),'Pack & collect','Check each order, collect the balance and confirm the handover.',button(ico('print')+'<span>Print packing tickets</span>','print','','data-k="packing"'))+
  `<div class="kpis">${tile('Pickups this week',num(os.length),{icon:'box',note:`${num(os.reduce((n,o)=>n+o.lines.reduce((m,l)=>m+l.qty,0),0))} pieces`,i:0})}${tile('Ready for pickup',num(os.filter(o=>o.status==='Ready').length),{icon:'check',tone:'pos',note:'Finished and packed',i:1})}${tile('Collected',num(os.filter(o=>o.status==='Collected').length),{icon:'users',note:'Handed over',i:2})}${tile('Balance to collect',money(p.totals.balanceDue),{icon:'wallet',tone:'pos',note:`Of ${money(p.totals.quotedRevenue)} quoted`,i:3})}</div>
  <section class="card">${cardhead('Every customer, accounted for',`${plural(os.length,'pickup')} · ${weekLabel(week)}`,'users')}${os.length?`<div class="orders-grid">${os.map(orderCard).join('')}</div>`:empty('No pickups this week','Pick the week your customers are collecting, at the top.','','box')}</section>`;},

 orders(){const st=UI.orders,t=today(),q=st.q.toLowerCase(),all=state.orders,open=o=>['Confirmed','Ready'].includes(o.status);
  const rows=all.filter(o=>(st.status==='all'||(st.status==='open'?open(o):o.status===st.status))&&(!q||`${o.reference} ${o.customer} ${o.status} ${o.lines.map(l=>recipe(l.recipeId)?.name).join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const per=15,pages=Math.max(1,Math.ceil(rows.length/per));st.page=Math.max(0,Math.min(st.page,pages-1));const view=rows.slice(st.page*per,st.page*per+per);
  const upcoming=all.filter(o=>open(o)&&o.dueDate>=t),ym=t.slice(0,7),collected=all.filter(o=>o.status==='Collected'&&o.dueDate.startsWith(ym));
  return pagehead('Your order book','Orders','Prices stay with each order. The kitchen plan uses each order’s bake and finish days.',button(ico('upload')+'<span>Import</span>','import-orders','quiet')+button(ico('down')+'<span>CSV</span>','export-orders','quiet')+button(ico('spark')+'<span>Try an order</span>','simulator','primary'))+
  `<div class="kpis">${tile('Upcoming pickups',num(upcoming.length),{icon:'calendar',note:upcoming[0]?`Next: ${esc(upcoming[0].customer)}, ${date(upcoming[0].dueDate)}`:'None booked yet',i:0})}${tile('Quoted, upcoming',money(upcoming.reduce((n,o)=>n+rev(o),0)),{icon:'up',tone:'pos',note:'Pickups from today on',i:1})}${tile('Balance to collect',money(all.filter(open).reduce((n,o)=>n+balance(o),0)),{icon:'wallet',tone:'pos',note:'On confirmed and ready orders',i:2})}${tile('Collected this month',money(collected.reduce((n,o)=>n+rev(o),0)),{icon:'check',tone:'pos',note:`${plural(collected.length,'order')} in ${monthName(ym,{month:'long'})}`,i:3})}</div>
  <section class="card table-card">${cardhead('Every order',`${plural(rows.length,'order')} shown`,'log',`<div class="filters"><div class="segment" role="group" aria-label="Status">${[['open','Open'],['all','All'],['Confirmed','Confirmed'],['Ready','Ready'],['Collected','Collected'],['Cancelled','Canceled']].map(([k,l])=>`<button data-action="status-filter" data-k="${k}" aria-pressed="${st.status===k}">${l}</button>`).join('')}</div><input id="search" type="search" placeholder="Search customer, reference or product" value="${esc(st.q)}" aria-label="Search orders"></div>`)}
   ${rows.length?`<div class="table-wrap"><table><thead><tr><th>Order / customer</th><th>Products</th><th>Pickup</th><th>Status</th><th class="num">Quoted</th><th class="num">Balance</th><th></th></tr></thead><tbody>${view.map(o=>`<tr><td><strong>${esc(o.customer)}</strong><small class="dim" style="display:block">${esc(o.reference)}</small></td><td><span class="clamp">${o.lines.map(l=>`${num(l.qty)} × ${esc(recipe(l.recipeId)?.name||'')}`).join('<br>')}</span></td><td data-v="${o.dueDate}" style="white-space:nowrap">${date(o.dueDate)}<small class="dim" style="display:block">Bake ${date(o.bakeDate)} · finish ${date(o.finishDate)}</small></td><td data-v="${o.status}">${statusPill(o.status)}</td><td class="num">${money(rev(o))}</td><td class="num">${money(balance(o))}</td><td class="num">${button('Open','order-form','small',`data-id="${esc(o.id)}"`)}</td></tr>`).join('')}</tbody></table></div>${pager(st,rows.length,per)}`
   :empty(all.length?'No orders match':'Your next booking starts with a better decision',all.length?'Try another status or search.':'Try its quantities, finishing time and price before you accept it.',all.length?'':button('Try an order','simulator','primary'),'log')}</section>`;},

 year(){const y=week.slice(0,4),os=state.orders.filter(o=>o.status!=='Cancelled'&&o.dueDate.startsWith(y)),ms=Array.from({length:12},(_,i)=>`${y}-${pad(i+1)}`);
  const head=pagehead(y,'Year at a glance',`Every month of ${y}, from your orders by pickup date. Canceled orders are left out.`,button('‹ '+(y-1),'year-shift','quiet','data-d="-1"')+button((+y+1)+' ›','year-shift','quiet','data-d="1"'));
  if(!os.length)return head+`<section class="card">${empty(`No orders in ${y}`,'Pick another year, or accept your first order.',button('Try an order','simulator','primary'),'outlook')}</section>`;
  // stacked by product, in the same colors as the best-sellers donut: a product keeps one color on this screen
  const nameOf=l=>recipe(l.recipeId)?.name||'Product',prodTot=new Map();os.forEach(o=>o.lines.forEach(l=>prodTot.set(nameOf(l),(prodTot.get(nameOf(l))||0)+l.qty*l.unitPrice)));
  const top=[...prodTot].sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>x[0]),key=l=>top.includes(nameOf(l))?nameOf(l):'__other';
  const mStats=ms.map(m=>{const mo=os.filter(o=>o.dueDate.startsWith(m));return {orders:mo.length,pieces:mo.reduce((n,o)=>n+o.lines.reduce((k,l)=>k+l.qty,0),0),sales:mo.reduce((n,o)=>n+rev(o),0),by:c=>mo.reduce((n,o)=>n+o.lines.filter(l=>key(l)===c).reduce((k,l)=>k+l.qty*l.unitPrice,0),0)};});
  const series=[...top.map((c,i)=>({name:c,color:CAT[i],values:mStats.map(s=>s.by(c))})),...(prodTot.size>5?[{name:'Other',color:CAT[5],values:mStats.map(s=>s.by('__other'))}]:[])];
  const T={orders:os.length,pieces:mStats.reduce((n,s)=>n+s.pieces,0),sales:mStats.reduce((n,s)=>n+s.sales,0)};
  return head+`<div class="kpis">${tile('Orders',num(T.orders),{icon:'log',note:`${plural(mStats.filter(s=>s.orders).length,'month')} with pickups`,i:0})}${tile('Pieces sold',num(T.pieces),{icon:'box',note:`About ${num(Math.round(T.pieces/Math.max(1,T.orders)))} per order`,i:1})}${tile('Quoted sales',money(T.sales),{icon:'up',tone:'pos',note:`${y} so far`,count:T.sales,i:2})}${tile('Average order',money(T.sales/T.orders),{icon:'tags',tone:'pos',note:'Quoted value per order',i:3})}</div>
  <section class="card">${cardhead('Sales by month','Quoted value of each month’s pickups, by product','insights')}${bars(series,ms.map(m=>monthName(m,{month:'short'})),{title:'Sales by month',W:1100,H:280})}</section>
  <div class="grid2"><section class="card table-card">${cardhead('Month by month','','table')}<div class="table-wrap"><table><thead><tr><th>Month</th><th class="num">Orders</th><th class="num">Pieces</th><th class="num">Sales</th><th class="num">Average order</th></tr></thead><tbody>${ms.map((m,i)=>{const s=mStats[i];return `<tr><td data-v="${m}">${monthName(m,{month:'long'})}</td><td class="num">${s.orders?num(s.orders):'—'}</td><td class="num">${s.pieces?num(s.pieces):'—'}</td><td class="num">${s.orders?money(s.sales):'—'}</td><td class="num">${s.orders?money(s.sales/s.orders):'—'}</td></tr>`;}).join('')}<tr class="total"><td>${y}</td><td class="num">${num(T.orders)}</td><td class="num">${num(T.pieces)}</td><td class="num">${money(T.sales)}</td><td class="num">${money(T.sales/T.orders)}</td></tr></tbody></table></div></section>
  <section class="card">${cardhead('Best sellers',`Share of ${y}’s quoted sales`,'tags')}${pie(fold([...prodTot]),{label:'Quoted sales',center:compact(T.sales),sub:'SALES'})}</section></div>`;},

 recipes(){const st=UI.recipes,q=st.q.toLowerCase(),cats=catList(),ci=c=>{const k=cats.indexOf(c);return k<0?999:k;};
  const keepsOf=r=>{const c=recipeCostPerPiece(r);return c===null||!r.unitPrice?null:(r.unitPrice-c)/r.unitPrice;};
  const rows=state.recipes.filter(r=>(st.status==='all'||(st.status==='archived')===r.archived)&&(st.cat==='all'||(r.category||'')===st.cat)&&(!q||`${r.name} ${r.category} ${r.method}`.toLowerCase().includes(q)));
  const by={name:(a,b)=>a.name.localeCompare(b.name),category:(a,b)=>ci(a.category)-ci(b.category)||a.name.localeCompare(b.name),cost:(a,b)=>(recipeCostPerPiece(a)??1e9)-(recipeCostPerPiece(b)??1e9),price:(a,b)=>b.unitPrice-a.unitPrice,keeps:(a,b)=>(keepsOf(b)??-1e9)-(keepsOf(a)??-1e9),time:(a,b)=>a.activeMinutes-b.activeMinutes}[st.sort]||((a,b)=>0);rows.sort(by);
  const media=r=>prefs.images[r.id]?`<img src="${prefs.images[r.id]}" alt="">`:`<span>${esc(initial(r.name))}</span>`;
  const card=r=>{const c=recipeCostPerPiece(r),keeps=keepsOf(r);
   return `<article class="card recipe ${r.archived?'archived':''}" style="--rc:${esc(r.color)}"><div class="recipe-img">${media(r)}${r.archived?pill('Archived'):''}</div>${catChip(r.category)}<h2>${esc(r.name)}</h2><p>${num(r.yield)} pieces per batch · ${plural(r.ingredients.length,'ingredient')}</p>
    <div class="facts"><div><small>Hands-on / batch</small><b>${mins(r.activeMinutes)}</b></div><div><small>Finish / piece</small><b>${num(r.finishMinutes)} min</b></div><div><small>Cost / piece</small><b>${c===null?'Price needed':money(c)}</b></div><div><small>Price / piece</small><b>${money(r.unitPrice)}</b></div></div>
    <div class="keeps">${keeps===null?'Add every ingredient price to see what each piece keeps.':`Each piece keeps <b>${pc(keeps)}</b> of its price before your time`}<div class="meter"><i class="${keeps!==null&&keeps<0?'over':''}" style="width:${keeps===null?0:Math.max(3,Math.min(100,keeps*100)).toFixed(0)}%"></i></div></div>
    <div class="actions">${button('Edit recipe','recipe-form','small primary',`data-id="${esc(r.id)}"`)}${button(r.archived?'Activate':'Archive','archive-recipe','small quiet',`data-id="${esc(r.id)}"`)}</div></article>`;};
  const grid=()=>`<div class="recipe-grid">${rows.map(card).join('')}</div>`;
  const table=()=>`<section class="card table-card"><div class="table-wrap"><table><thead><tr><th></th><th>Recipe</th><th>Category</th><th class="num">Yield</th><th class="num">Hands-on</th><th class="num">Cost / piece</th><th class="num">Price</th><th class="num">Keeps</th><th></th></tr></thead><tbody>${rows.map(r=>{const c=recipeCostPerPiece(r),k=keepsOf(r);
   return `<tr${r.archived?' class="dim"':''}><td><span class="recipe-thumb" style="--rc:${esc(r.color)}">${media(r)}</span></td><td><strong>${esc(r.name)}</strong>${r.archived?'<small class="dim" style="display:block">Archived</small>':''}</td><td data-v="${String(ci(r.category)).padStart(3,'0')}">${catChip(r.category)}</td><td class="num">${num(r.yield)}</td><td class="num" data-v="${r.activeMinutes}">${mins(r.activeMinutes)}</td><td class="num" data-v="${c??-1}">${c===null?pill('Price needed','warn'):money(c)}</td><td class="num" data-v="${r.unitPrice}">${money(r.unitPrice)}</td><td class="num" data-v="${k??-9}">${k===null?'—':`<span class="pct"><i style="width:${Math.max(0,Math.min(100,k*100)).toFixed(0)}%"></i></span>${pc(k)}`}</td><td class="num" style="white-space:nowrap"><button class="icon-action" data-action="recipe-form" data-id="${esc(r.id)}" aria-label="Edit ${esc(r.name)}" title="Edit">${ico('edit')}</button></td></tr>`;}).join('')}</tbody></table></div></section>`;
  const seg=(act,cur,opts)=>`<div class="segment" role="group">${opts.map(([k,l])=>`<button data-action="${act}" data-k="${k}" aria-pressed="${cur===k}">${l}</button>`).join('')}</div>`;
  return pagehead('Your library','Recipes','Your own tested formulas, yields and times. Each recipe powers the plan, the shopping list and every quote.',button(ico('palette')+'<span>Categories</span>','go','quiet','data-go="settings" data-anchor="categories"')+button(ico('plus')+'<span>Add recipe</span>','recipe-form','primary'))+
  `<div class="recipe-tools"><input id="search" type="search" placeholder="Search recipes, categories or methods" value="${esc(st.q)}" aria-label="Search recipes">
   <select id="recipe-cat" aria-label="Category"><option value="all">All categories</option>${cats.map(c=>`<option ${st.cat===c?'selected':''}>${esc(c)}</option>`).join('')}${state.recipes.some(r=>!r.category)?`<option value="" ${st.cat===''?'selected':''}>Uncategorized</option>`:''}</select>
   <select id="recipe-sort" aria-label="Sort by">${[['category','By category'],['name','Name A–Z'],['keeps','Keeps most'],['price','Highest price'],['cost','Lowest cost'],['time','Quickest to make']].map(([k,l])=>`<option value="${k}" ${st.sort===k?'selected':''}>${l}</option>`).join('')}</select>
   ${seg('recipe-status',st.status,[['active','Active'],['archived','Archived'],['all','All']])}${seg('recipe-view',prefs.recipeView,[['grid','Grid'],['table','Table']])}</div>
  <p class="small muted" style="margin:0 0 12px">${plural(rows.length,'recipe')} shown of ${state.recipes.length} · costs use your latest pantry prices</p>
  ${rows.length?(prefs.recipeView==='table'?table():grid()):`<section class="card">${empty(state.recipes.length?'No recipes match':'Start with one familiar recipe',state.recipes.length?'Try another search, category or status.':'A batch yield, ingredient amounts and realistic making time are enough to begin.',state.recipes.length?'':button('Add your first recipe','recipe-form','primary'),'tags')}</section>`}
  ${demo?'<div class="notice" style="margin-top:16px"><span>These are made-up costing examples for learning the app, not tested recipes. Use your own recipes, methods and current prices.</span></div>':''}`;},

 pantry(){const st=UI.pantry,q=st.q.toLowerCase(),rows=state.ingredients.filter(i=>!q||`${i.name} ${i.supplier}`.toLowerCase().includes(q)).sort((a,b)=>a.archived-b.archived||a.name.localeCompare(b.name));
  const per=15,pages=Math.max(1,Math.ceil(rows.length/per));st.page=Math.max(0,Math.min(st.page,pages-1));const view=rows.slice(st.page*per,st.page*per+per);
  const value=i=>i.packCost===null?null:i.stock*i.packCost/i.packSize,missing=state.ingredients.filter(i=>!i.archived&&i.packCost===null).length,short=plan().shopping.filter(x=>x.shortfall>0).length;
  return pagehead('Your library','Pantry','Pack sizes turn recipe amounts into a practical shopping list. Keep stock and prices current.',button(ico('plus')+'<span>Add ingredient</span>','ingredient-form','primary'))+
  `<div class="kpis">${tile('Ingredients',num(state.ingredients.filter(i=>!i.archived).length),{icon:'tags',note:`${num(new Set(state.ingredients.map(i=>i.supplier).filter(Boolean)).size)} suppliers`,i:0})}${tile('Pantry value',money(state.ingredients.reduce((n,i)=>n+(value(i)||0),0)),{icon:'coins',note:'Stock at your latest pack prices',i:1})}${tile('Short this week',num(short),{icon:'cart',tone:short?'neg':'pos',note:short?'See the shopping list':'Everything is covered',go:'shopping',i:2})}${tile('Missing prices',num(missing),{icon:'coins',tone:missing?'neg':'pos',note:missing?'Estimates stay incomplete until added':'Every price is in',i:3})}</div>
  <section class="card table-card">${cardhead('Ingredients & pack prices',plural(rows.length,'ingredient'),'cart',`<div class="filters"><input id="search" type="search" placeholder="Search ingredients or suppliers" value="${esc(st.q)}" aria-label="Search ingredients"></div>`)}
   ${rows.length?`<div class="table-wrap"><table><thead><tr><th>Ingredient</th><th class="num">Pack size</th><th class="num">Pack price</th><th class="num">In stock</th><th class="num">Stock value</th><th>Supplier</th><th></th></tr></thead><tbody>${view.map(i=>`<tr><td><strong>${esc(i.name)}</strong>${i.archived?'<small class="dim" style="display:block">Archived</small>':''}</td><td class="num" data-v="${i.packSize}">${qty(i.packSize,i.unit)}</td><td class="num" data-v="${i.packCost??-1}">${i.packCost===null?pill('Price needed','warn'):money(i.packCost)}</td><td class="num" data-v="${i.stock}"><strong>${qty(i.stock,i.unit)}</strong></td><td class="num" data-v="${value(i)??-1}">${cash(value(i))}</td><td>${esc(i.supplier||'—')}</td><td class="num" style="white-space:nowrap"><button class="icon-action" data-action="receive-ingredient" data-id="${esc(i.id)}" aria-label="Receive ${esc(i.name)}" title="Receive stock">${ico('down')}</button><button class="icon-action" data-action="ingredient-form" data-id="${esc(i.id)}" aria-label="Edit ${esc(i.name)}" title="Edit">${ico('edit')}</button></td></tr>`).join('')}</tbody></table></div>${pager(st,rows.length,per)}`
   :empty(state.ingredients.length?'No ingredients match':'Make your pantry work for the plan',state.ingredients.length?'Try another search.':'Add pack sizes, prices and what you have, and the shopping list buys only what’s missing.',state.ingredients.length?'':button('Add your first ingredient','ingredient-form','primary'),'cart')}</section>
  <div class="notice"><span>Amounts use grams, milliliters or each. 1 kg = 1000 g, 1 L = 1000 ml, 1 dozen = 12 each. Cups-to-grams and mass-to-volume conversions are never guessed.</span></div>`;},

 settings(){const s=state.settings,hidden=new Set(prefs.hiddenNav),optional=CONFIG.nav.filter(([id])=>CONFIG.optionalNav.includes(id));
  const chips={kiln:['#FBF8F5','#A4471F','#3A2419','#F2B441'],ledger:['#F6F7F5','#1F7A5C','#182635','#E3A73B'],sage:['#FAFAF8','#2F5D50','#1F4A3E','#F2B441'],linen:['#F7F4ED','#6B5B45','#45392A','#E8A24A'],fjord:['#F6F8FA','#2C5470','#1C3C52','#F0A93C'],slate:['#F8F9FA','#3F4A55','#2E3841','#EFA93F'],night:['#141218','#C3A9E8','#221C2C','#F0B98F'],midnight:['#0C1720','#9DB8F5','#0B303D','#F5C382']};
  const currencies=['USD','EUR','GBP','CAD','AUD','NZD','INR','NGN','ZAR','JPY','CHF','SEK','SGD','MXN','BRL'];if(!currencies.includes(s.currency))currencies.unshift(s.currency);
  return pagehead('Make it yours','Settings & backup','')+
  `<div class="grid2 equal"><section class="card"><h2>Your bakery</h2><form id="settings-form" style="margin-top:20px"><div class="fields">${fld('business','Business name',s.business,{attrs:'required maxlength="150"',hint:'Shown on quotes, packing tickets and batch sheets.',full:true})}
    ${sel('currency','Currency',currencies.map(c=>[c,c]),s.currency)}${moneyFld('hourlyRate','Value of an hour of your work',s.hourlyRate,'Used as a labor allowance in quotes.')}
    ${fld('targetMargin','Target profit margin (%)',s.targetMargin,{type:'number',attrs:'min="0" max="95" step="0.1" required',hint:'Share of the price left after costs and labor.'})}${fld('cardRate','Card fee (%)',s.cardRate,{type:'number',attrs:'min="0" max="50" step="0.01" required'})}
    ${moneyFld('fixedFee','Fixed card fee per order',s.fixedFee,'Counted once per card order.')}</div><div class="formfoot"><button class="btn primary">Save</button></div></form>
    <h3 class="sub-head">Choose your palette</h3><div class="theme-grid">${CONFIG.themes.map(n=>{const [paper,accent,bold,pop]=chips[n];return `<button class="theme-card" data-action="theme" data-k="${n}" aria-pressed="${prefs.theme===n}" aria-label="${n} palette"><span class="theme-chip" style="background:${paper}"><i style="background:${bold}"></i><i style="background:${accent}"></i><i style="background:${pop}"></i></span><b>${n[0].toUpperCase()+n.slice(1)}</b></button>`;}).join('')}</div></section>
   <section class="card"><div class="card-ico">${ico('shield')}</div><h2>Keep your progress safe</h2><p class="subtitle">Changes save in this browser on this computer. The HTML file itself holds no entries, and clearing browser data can erase them.</p>
    <h3 class="sub-head first">Automatic backups</h3><div class="row flat"><div><strong>Folder backup</strong><small>Keeps today’s dated backup file current after every change. Choose a cloud-synced folder for an off-computer copy.</small></div><span class="pill" id="folder-status">${esc(folderStatus)}</span></div>
    <div class="actions" style="margin:12px 0">${folderSupported()?button(folder?(folderStatus==='Connected'?'Change folder':'Reconnect folder'):'Choose backup folder',folder&&folderStatus!=='Connected'?'reconnect-folder':'choose-folder','small',demo?'disabled':''):'<span class="small dim">Available in Chrome and Edge on a computer.</span>'}</div>
    <h3 class="sub-head">Manual backup</h3><div class="row flat"><div><strong>Download a full backup</strong><small>Every ingredient, recipe, order and batch record, plus your palette, in one file.</small></div></div><div class="actions" style="margin:12px 0">${button('Download backup','backup','primary')}${button('Restore backup','restore')}</div>
    <h3 class="sub-head">Move your orders</h3><div class="row"><div><strong>Orders as CSV</strong><small>For a spreadsheet. It isn’t a backup: status, contact, costs, private notes and stock aren’t included.</small></div>${button('Export','export-orders','small')}</div>
    <div class="row"><div><strong>Import orders from CSV</strong><small>Use the template and your exact recipe names. Existing references are skipped.</small></div>${button('Import','import-orders','small')}</div>
    <h3 class="sub-head">Start fresh</h3><div class="row"><div><strong>Clear your bakery in one step</strong><small>${demo?'Return to your own bakery first. Sample mode is never saved.':'Removes ingredients, recipes, orders and batch records. You can undo it straight after.'}</small></div>${button('Start fresh','fresh','small danger',demo?'disabled':'')}</div></section></div>
  <section class="card"><div class="cardhead"><div><h2>Your working hours</h2><p>Hands-on hours you can work each day. The pattern repeats every week; oven time isn’t counted.</p></div><span class="pill">${hrs(s.capacity.reduce((n,x)=>n+x,0))} a week</span></div>
   <form id="capacity-form"><div class="capacity">${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,n)=>`<label>${d}<input name="cap${n}" type="number" min="0" max="24" step="0.25" value="${+(s.capacity[n]/60).toFixed(2)}" required></label>`).join('')}</div><div class="formfoot"><button class="btn primary">Save hours</button></div></form></section>
  <section class="card" id="categories"><div class="cardhead"><div><h2>Recipe categories</h2><p>The order here is the order in the category filter and the “By category” sort. Click a swatch to change its color. Renaming or deleting updates every recipe in it.</p></div><span class="pill">${plural(catList().length,'category','categories')}</span></div>
   ${catList().map((c,i,l)=>{const n=state.recipes.filter(r=>r.category===c).length;return `<div class="row"><div class="cat-name"><input type="color" class="cat-swatch" data-cat-color="${i}" value="${catColor(c)}" aria-label="Color for ${esc(c)}" title="Change color"><div><strong>${esc(c)}</strong><small>${plural(n,'recipe')}</small></div></div><div class="actions"><button class="icon-action" data-action="cat-move" data-i="${i}" data-d="-1" aria-label="Move ${esc(c)} up" ${i?'':'disabled'}>${ico('up')}</button><button class="icon-action" data-action="cat-move" data-i="${i}" data-d="1" aria-label="Move ${esc(c)} down" ${i<l.length-1?'':'disabled'}>${ico('down')}</button><button class="icon-action" data-action="cat-rename" data-i="${i}" aria-label="Rename ${esc(c)}" title="Rename">${ico('edit')}</button><button class="icon-action danger" data-action="cat-delete" data-i="${i}" aria-label="Delete ${esc(c)}" title="Delete">${ico('trash')}</button></div></div>`;}).join('')||'<p class="dim small">No categories yet.</p>'}
   <form id="cat-add-form" class="actions" style="margin-top:12px;flex-wrap:nowrap"><input type="color" class="cat-swatch" name="color" value="${CAT_PALETTE[catList().length%CAT_PALETTE.length]}" aria-label="Color for the new category" title="Color"><input name="name" placeholder="New category, e.g. Breads" maxlength="80" required style="flex:1"><button class="btn primary">Add category</button></form></section>
  <section class="card"><div class="cardhead"><div><h2>Simplify your sidebar</h2><p>Switch extra views on or off. Changes appear immediately.</p></div><span class="pill">${optional.filter(([id])=>!hidden.has(id)).length} of ${optional.length} shown</span></div><div class="toggle-grid">${optional.map(([id,name,icon])=>`<label class="nav-toggle"><input type="checkbox" data-nav-toggle="${id}" ${hidden.has(id)?'':'checked'}><span>${ico(icon)}<b>${name}</b><i aria-hidden="true"></i></span></label>`).join('')}</div></section>
  <section class="card"><div class="cardhead"><div><h2>Getting started</h2><p>A short tour, and a made-up bakery to explore.</p></div>${button(demo?'Return to my bakery':'Open the sample bakery','sample')}</div><div class="row"><div><strong>Show the welcome tour again</strong><small>${CONFIG.welcome.length} short slides, including backups.</small></div>${button('Show tour','tour','small')}</div>
   <p class="small muted" style="margin-top:12px">Bakeweek Studio ${CONFIG.version} by JPS Digital Pages · support through <a href="${CONFIG.support}" target="_blank" rel="noopener">JPSDigitalPages on Etsy</a> · personal or internal business use by the purchaser. Estimates use your own inputs; it doesn’t take payments, calculate taxes or make food labels.</p></section>`;},

 guide(){return pagehead('Help','How to use Bakeweek Studio','From inquiry to a calmer kitchen, in three moves.')+
  `<div class="steps" style="margin-bottom:16px">${[['01 / LIBRARY','Build your library','Add pantry pack prices and stock. Save your tested recipes: yield, hands-on minutes per batch and finishing minutes per piece.',button('Open pantry','go','small','data-go="pantry"')],
   ['02 / DECIDE','Try it before saying yes','Use Try an order (or press N). Change quantity, finishing time, price or dates and see the extra work, whole-batch costs and shopping before you accept.',button('Try an order','simulator','small primary')],
   ['03 / MAKE','Buy, bake, pack','Receive what you actually bought. Mark each batch made, which takes its ingredients from the pantry once. Then mark the order Ready, then Collected.',button('This week','go','small','data-go="week"')]].map(([n,h,p,b])=>`<div class="step"><span>${n}</span><h3>${h}</h3><p>${p}</p>${b}</div>`).join('')}</div>
  <section class="card table-card">${cardhead('Good to know','','help')}<div class="table-wrap"><table data-nosort><thead><tr><th>Question</th><th>Answer</th></tr></thead><tbody>
   <tr><td>Where is my data?</td><td>In this browser on this computer. The HTML file holds no entries. Clearing browser data can erase them, so choose a backup folder or download backups.</td></tr>
   <tr><td>New computer or browser?</td><td>Download a backup here, open Bakeweek Studio there, and use Restore backup in Settings.</td></tr>
   <tr><td>What are the extra pieces?</td><td>Recipes bake in whole batches, so a batch can make more than was ordered. Extras aren’t moved to other orders automatically.</td></tr>
   <tr><td>Is oven time scheduled?</td><td>No. Oven minutes are shown for reference; the plan schedules your hands-on time against the hours you set.</td></tr>
   <tr><td>How is the minimum quote worked out?</td><td>Ingredients, packaging and card fees, plus your hourly value for the hands-on time, then your target margin on top. Taxes and overheads you haven’t entered aren’t included.</td></tr>
   <tr><td>Can I print?</td><td>Yes: the kitchen packet (shopping, batch sheets and packing tickets), each of those on its own, and a customer quote for any order. Any screen also prints as it is.</td></tr>
   <tr><td>Food safety?</td><td>Follow your own tested methods, storage and food-safety procedures. The sample recipes are costing examples, not tested recipes.</td></tr></tbody></table></div></section>`;},
};

/* ================================================================================
   Dialogs
   ================================================================================ */
function ingredientForm(id){const i=ingredient(id)||{name:'',unit:'g',packSize:1000,packCost:'',stock:0,supplier:''};
 modal(id?'Edit ingredient':'Add a pantry ingredient','Pack size and price turn recipe amounts into whole packs to buy.',`<form id="ingredient-form" data-id="${esc(id||'')}"><div class="fields">${fld('name','Ingredient name',i.name,{attrs:'required maxlength="150"',full:true})}
 ${sel('unit','Base unit',[['g','Grams (g)'],['ml','Milliliters (ml)'],['each','Each']],i.unit)}${fld('packSize','Amount in one pack',i.packSize,{type:'number',attrs:'min="0.000001" step="any" required',hint:'In the base unit: 2.5 kg = 2500 g.'})}
 ${moneyFld('packCost','Price per pack',i.packCost??'','Leave blank if unknown. Enter 0 only when it’s genuinely free.')}${fld('stock','In your pantry now',i.stock,{type:'number',attrs:'min="0" step="any" required',hint:'In the same base unit.'})}
 ${fld('supplier','Supplier or shopping stop',i.supplier,{attrs:'maxlength="150"',full:true})}</div><div class="notice" style="margin:14px 0 0"><span>The base unit locks once a recipe uses this ingredient.</span></div>${formFoot(id?'Save ingredient':'Add ingredient')}</form>`);}
const ingRows=()=>recipeRows.map((l,n)=>`<div class="line-row ing" data-index="${n}"><label>Ingredient ${n+1}<select data-ri="ingredientId">${state.ingredients.filter(i=>!i.archived||i.id===l.ingredientId).map(i=>`<option value="${esc(i.id)}" ${i.id===l.ingredientId?'selected':''}>${esc(i.name)} (${i.unit})</option>`).join('')}</select></label><label>Per batch (${esc(ingredient(l.ingredientId)?.unit||'')})<input data-ri="qty" type="number" min="0.000001" step="any" value="${l.qty}" required></label><button type="button" class="icon-action danger" data-action="remove-recipe-ingredient" data-index="${n}" aria-label="Remove ingredient ${n+1}">${ico('trash')}</button></div>`).join('');
function recipeForm(id){if(!state.ingredients.some(i=>!i.archived)){toast('Add at least one pantry ingredient first.');return ingredientForm();}
 const r=recipe(id)||{name:'',category:'',color:'#A46D4C',yield:12,activeMinutes:25,ovenMinutes:20,finishMinutes:2,unitPrice:3,packagingCost:.2,method:'',ingredients:[{ingredientId:state.ingredients.find(i=>!i.archived).id,qty:100}]};recipeRows=clone(r.ingredients);recipeImg=undefined;
 modal(id?'Edit recipe':'Build a reusable recipe','Changes update estimates for unfinished orders. Saved order prices and completed batches stay as they are.',`<form id="recipe-form" data-id="${esc(id||'')}"><div class="fields">${fld('name','Recipe or product name',r.name,{attrs:'required maxlength="150"',full:true})}
 ${sel('category','Category',[['','Uncategorized'],...catList().map(c=>[c,c])],r.category||'',{attrs:''})}${fld('color','Recipe color',r.color,{type:'color'})}
 ${fld('yield','Sellable pieces per batch',r.yield,{type:'number',attrs:'min="1" step="1" required'})}${fld('activeMinutes','Hands-on minutes per batch',r.activeMinutes,{type:'number',attrs:'min="0" step="any" required',hint:'Mixing, portioning and active prep.'})}
 ${fld('ovenMinutes','Oven minutes per batch',r.ovenMinutes,{type:'number',attrs:'min="0" step="any" required',hint:'A reference, not an oven schedule.'})}${fld('finishMinutes','Finishing minutes per piece',r.finishMinutes,{type:'number',attrs:'min="0" step="any" required',hint:'Decorating, finishing and packing.'})}
 ${moneyFld('unitPrice','Default price per piece',r.unitPrice)}${moneyFld('packagingCost','Packaging cost per piece',r.packagingCost)}</div>
 <div class="form-section"><h3>Picture</h3><div class="pic-row"><div id="recipe-pic">${imgBox(id?prefs.images[id]:'',r.color)}</div><div class="actions"><label class="btn small">${ico('upload')}Choose a picture<input type="file" id="recipe-pic-file" accept="image/*" hidden></label>${button('Remove','recipe-pic-remove','small quiet')}</div><p class="small dim">Shown on recipe cards and in the table. Resized to 640×480 and kept on this computer. New categories: Settings → Recipe categories.</p></div></div><div class="form-section"><h3>Ingredients for one batch</h3><div id="recipe-rows">${ingRows()}</div>${button(ico('plus')+'Add ingredient','add-recipe-ingredient','small quiet')}</div>
 <div class="fields">${area('method','Your tested method and batch notes',r.method,'Batch sheets scale the amounts for you. Follow your own recipe, storage and food-safety procedures.')}</div>${formFoot(id?'Save recipe':'Add recipe')}</form>`,true);}
function newOrder(){const r=state.recipes.find(r=>!r.archived),refs=new Set(state.orders.map(o=>o.reference.toLowerCase())),ref=()=>{let n=state.orders.length+1;while(refs.has(`bw-${String(n).padStart(3,'0')}`))n++;return `BW-${String(n).padStart(3,'0')}`;};
 return {reference:ref(),customer:'',contact:'',dueDate:C.addDays(week,5),bakeDate:C.addDays(week,3),finishDate:C.addDays(week,4),status:'Confirmed',paid:0,payment:'Card',setupMinutes:15,extraCost:0,customerNote:'',kitchenNote:'',lines:r?[{recipeId:r.id,qty:48,unitPrice:r.unitPrice,finishMinutes:r.finishMinutes}]:[]};}
const lineRows=(lines,scope)=>lines.map((l,n)=>`<div class="line-row" data-index="${n}"><label>Product<select data-line="recipeId" data-scope="${scope}">${state.recipes.filter(r=>!r.archived||r.id===l.recipeId).map(r=>`<option value="${esc(r.id)}" ${r.id===l.recipeId?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label>Pieces<input data-line="qty" data-scope="${scope}" type="number" min="1" step="1" value="${Number.isFinite(l.qty)?l.qty:''}" required></label><label>Price / piece<input data-line="unitPrice" data-scope="${scope}" type="number" min="0" step=".01" value="${Number.isFinite(l.unitPrice)?l.unitPrice:''}" required></label><label>Finish min / piece<input data-line="finishMinutes" data-scope="${scope}" type="number" min="0" step="any" value="${Number.isFinite(l.finishMinutes)?l.finishMinutes:''}" required></label><button type="button" class="icon-action danger" data-action="remove-line" data-scope="${scope}" data-index="${n}" aria-label="Remove product ${n+1}">${ico('trash')}</button></div>`).join('');
const orderFields=o=>`${fld('reference','Order reference',o.reference,{attrs:'required maxlength="100"'})}${fld('customer','Customer',o.customer,{attrs:'required maxlength="150"'})}${fld('contact','Contact or pickup details',o.contact,{attrs:'maxlength="250"',full:true})}
 ${fld('bakeDate','Bake date',o.bakeDate,{type:'date',attrs:'required'})}${fld('finishDate','Finish & pack date',o.finishDate,{type:'date',attrs:'required'})}${fld('dueDate','Pickup date',o.dueDate,{type:'date',attrs:'required'})}
 ${sel('payment','Payment method',[['Card','Card'],['Cash','Cash'],['Other','Other']],o.payment)}${fld('setupMinutes','Extra setup minutes',o.setupMinutes,{type:'number',attrs:'min="0" step="any" required'})}${moneyFld('extraCost','Extra packaging or order cost',o.extraCost)}${moneyFld('paid','Paid so far',o.paid)}
 ${area('customerNote','Note for the customer',o.customerNote)}${area('kitchenNote','Private kitchen note',o.kitchenNote,'Only on kitchen paperwork, never on the customer quote.')}`;
function orderForm(id){const o=order(id);if(!o)return simulator();orderRows=clone(o.lines);const q=C.quoteOrder(state,o),locked=state.completedRuns.some(r=>r.allocations.some(a=>a.orderId===o.id));
 modal(`${esc(o.reference)} · ${esc(o.customer)}`,`Pickup ${longDay(o.dueDate)} ${date(o.dueDate)} · bake ${date(o.bakeDate)} · finish ${date(o.finishDate)}`,
 `<div class="kpis" style="grid-template-columns:repeat(3,minmax(0,1fr))">${tile('Order total',money(q.revenue),{tone:'pos',icon:'up'})}${tile('Still to collect',money(balance(o)),{tone:'pos',icon:'wallet'})}${tile('Estimated surplus',cash(q.surplus),{tone:'net',icon:'insights',note:'After costs and your time'})}</div>
 <div class="actions" style="margin-bottom:8px">${statusPill(o.status)}${button(ico('print')+'Print quote','print','small','data-k="quote" data-id="'+esc(id)+'"')}${button('Record payment','payment','small',`data-id="${esc(id)}"`)}${o.status==='Confirmed'?button('Mark ready','order-status','small',`data-id="${esc(id)}" data-status="Ready"`):''}${o.status==='Ready'?button('Mark collected','order-status','small',`data-id="${esc(id)}" data-status="Collected"`):''}${o.status!=='Confirmed'?button('Return to Confirmed','order-status','small quiet',`data-id="${esc(id)}" data-status="Confirmed"`):''}</div>
 ${locked?'<div class="notice"><span>This order has batches marked made. Undo them before changing quantities, dates or prices. Payments and status still work.</span></div>':''}
 <form id="order-form" data-id="${esc(id)}"><fieldset ${locked?'disabled':''} style="border:0;padding:0;margin:12px 0 0"><div class="form-section" style="margin-top:0;border:0;padding:0"><h3>Products</h3><div id="order-rows">${lineRows(orderRows,'order')}</div>${button(ico('plus')+'Add product','add-line','small quiet','data-scope="order"')}</div><div class="fields">${orderFields(o)}</div></fieldset>
 <div class="formfoot">${!locked&&o.status!=='Cancelled'?button('Cancel order','cancel-order','danger',`data-id="${esc(id)}"`):''}${!locked?button('Delete','delete-order','danger quiet',`data-id="${esc(id)}"`):''}<button type="button" class="btn" data-action="dismiss">Close</button>${!locked?'<button class="btn primary" type="submit">Save changes</button>':''}</div></form>`,true);}
function simulator(){if(!state.recipes.some(r=>!r.archived)){toast('Save a recipe first, so the order uses your real costs.');return recipeForm();}
 simDraft=newOrder();simDraft.customer='New inquiry';if(demo)simDraft.lines[0].finishMinutes=6;
 modal('Should you say yes to this order?',`A safe place to experiment: nothing is saved until you accept. Week of ${weekLabel(week)}.`,`<div class="sim"><form id="sim-form"><div class="fields">${fld('sim-customer','Customer or inquiry',simDraft.customer,{attrs:'data-sim="customer" required',full:true})}</div>
 <div class="form-section" style="margin-top:14px"><h3>Products</h3><div id="sim-rows">${lineRows(simDraft.lines,'sim')}</div>${button(ico('plus')+'Add product','add-line','small quiet','data-scope="sim"')}</div>
 <div class="fields">${fld('sim-bakeDate','Bake date',simDraft.bakeDate,{type:'date',attrs:`data-sim="bakeDate" min="${week}" max="${C.addDays(week,6)}" required`})}${fld('sim-finishDate','Finish & pack',simDraft.finishDate,{type:'date',attrs:`data-sim="finishDate" min="${week}" max="${C.addDays(week,6)}" required`})}
 ${fld('sim-dueDate','Pickup date',simDraft.dueDate,{type:'date',attrs:'data-sim="dueDate" required'})}${sel('sim-payment','Payment method',[['Card','Card'],['Cash','Cash'],['Other','Other']],simDraft.payment,{attrs:'data-sim="payment"'})}
 ${fld('sim-setupMinutes','Extra setup minutes',simDraft.setupMinutes,{type:'number',attrs:'data-sim="setupMinutes" min="0" step="any" required'})}${fld('sim-extraCost','Extra packaging or order cost',0,{type:'number',attrs:'data-sim="extraCost" min="0" step=".01" required'})}</div>
 <div class="form-section"><h3>Explore a workable version</h3><div class="sim-ideas">${button('Simpler finish · 2 min','sim-simple','small')}${button('Use recipe times','sim-default','small')}${button('Try available days','sim-days','small')}${button('Use the target quote','sim-price','small')}</div><p class="small dim" style="margin-top:8px">These change this draft only. Pick dates and decoration time that suit your recipe and your promise to the customer.</p></div></form>
 <aside class="sim-out" id="sim-out" aria-live="polite"></aside></div>`,true);updateSimulation();}
function suggestedQuote(result){const q=result.quote,d=result.delta,rate=simDraft.payment==='Card'?state.settings.cardRate/100:0,fixed=simDraft.payment==='Card'?state.settings.fixedFee:0;if(q.minPriceAtTarget===null||d.ingredientCost===null)return null;return Math.max(q.minPriceAtTarget,(d.ingredientCost+d.packagingCost+d.laborAllowance+fixed)/(1-rate-state.settings.targetMargin/100));}
function updateSimFields(){for(const e of $$('[data-sim]'))e.value=simDraft[e.dataset.sim];$('#sim-rows').innerHTML=lineRows(simDraft.lines,'sim');updateSimulation();}
function updateSimulation(){const out=$('#sim-out');if(!out)return;try{simResult=C.simulateOrder(state,simDraft,week);const {quote:q,delta:d}=simResult,target=suggestedQuote(simResult),priceOK=target!==null&&q.revenue+0.00001>=target,good=simResult.fits&&priceOK;
  out.innerHTML=`<div class="verdict ${!simResult.fits?'bad':!priceOK?'warn':''}"><div class="eyebrow">Before you promise it</div><h3>${!simResult.fits?'This version overloads your week':!priceOK?'It fits. The price needs a look':'A workable version of this order'}</h3><p>${!simResult.fits?simResult.conflicts.map(x=>`${longDay(x.date)}: ${mins(x.overMinutes)} over your hours`).join(' · '):'The hands-on work fits the hours you set for each day.'}</p></div>
  <div class="sim-tiles">${tile('Extra hands-on work',mins(d.activeMinutes),{icon:'clock',note:'Whole batches plus finishing'})}${tile('Extra batches',num(d.batches),{icon:'oven',note:`${num(d.units)} pieces ordered`})}${tile('Extra shopping',cash(d.shoppingCost),{icon:'cart',tone:'neg',note:'Change in whole packs to buy'})}${tile('Extra surplus',cash(d.surplus),{icon:'insights',tone:d.surplus!==null&&d.surplus<0?'neg':'net',note:'After costs, fees and your time'})}</div>
  <div class="receipt"><div class="row"><span>Customer quote</span><strong class="number">${money(q.revenue)}</strong></div><div class="row"><span>Extra ingredients</span><strong class="number">${cash(d.ingredientCost)}</strong></div><div class="row"><span>Packaging and extras</span><strong class="number">${money(d.packagingCost)}</strong></div><div class="row"><span>Payment fees</span><strong class="number">${money(d.fees)}</strong></div><div class="row"><span>Your time (${money(state.settings.hourlyRate)}/h)</span><strong class="number">${money(d.laborAllowance)}</strong></div><div class="row total"><span>Suggested minimum quote</span><strong>${cash(target)}</strong></div></div>
  ${q.unknownCosts.length?`<div class="notice warning"><span>Missing prices: ${esc(q.unknownCosts.join(', '))}. Add them before relying on the estimate.</span></div>`:d.ingredientCost===null?'<div class="notice warning"><span>Other batches this week have missing prices. Complete them in Pantry before relying on this comparison.</span></div>':''}
  ${button(good?'Accept and build the plan':'Accept this version anyway','accept-sim',good?'primary full':'full')}<p class="small dim" style="margin-top:8px">Accepting adds the order, its batches, shopping and packing ticket. No payment is taken. The minimum quote covers the whole batches this order needs, your time and your ${state.settings.targetMargin}% margin; taxes and unentered overheads aren’t included.</p>`;
  const e=$('#form-error');if(e)e.hidden=true;}catch(e){simResult=null;out.innerHTML=`<div class="notice warning"><span><b>Complete this draft.</b> ${esc(e.message)}</span></div>`;}}
function paymentForm(id){const o=order(id);modal('Record a payment',`${esc(o.customer)} · ${esc(o.reference)} · order total ${money(rev(o))}`,`<form id="payment-form" data-id="${esc(id)}"><div class="fields">${moneyFld('paid','Total paid so far',o.paid,'The running total, including earlier deposits.',true)}</div>${formFoot('Save payment')}</form>`);}
function receiveForm(id){const i=ingredient(id);modal('Receive pantry stock',`${esc(i.name)} · ${qty(i.stock,i.unit)} in the pantry now`,`<form id="receive-form" data-id="${esc(id)}"><div class="fields">${fld('qty',`Amount received (${i.unit})`,i.packSize,{type:'number',attrs:'min="0.000001" step="any" required',hint:'Adds to your stock; it doesn’t replace it.',full:true})}</div>${formFoot('Add to pantry')}</form>`);}
function capacityForm(){go('settings');setTimeout(()=>{const f=$('#capacity-form');f?.scrollIntoView({block:'center'});f?.querySelector('input')?.focus();},60);}
function importForm(){importPreview=null;modal('Bring your orders in once','Use the CSV template and the exact recipe names in your library. Repeat an order reference for several products; existing references are skipped.',`<div class="actions" style="margin-bottom:12px">${button(ico('down')+'Download the template','csv-template','small')}${button(ico('upload')+'Choose a CSV file','csv-file','small')}</div><div class="fields">${area('csvText','Or paste the CSV here','','Up to 4 MB. On a multi-product order, repeat the same paid amount on each row; it counts once.')}</div><div id="import-result" style="margin-top:12px"></div><div class="formfoot"><button type="button" class="btn" data-action="dismiss">Cancel</button>${button('Preview import','preview-import','primary')}</div>`,true);}
function previewImport(){const text=$('[name=csvText]').value;try{const copy=clone(state),old=new Set(copy.orders.map(o=>o.id)),r=C.importOrders(copy,text);importPreview={text,r};
  $('#import-result').innerHTML=`<div class="notice"><span><b>${plural(r.imported,'order')} ready · ${plural(r.skipped,'existing reference')} skipped.</b> Nothing is added yet.<br>${copy.orders.filter(o=>!old.has(o.id)).slice(0,10).map(o=>`${esc(o.reference)}: ${esc(o.customer)} (${num(o.lines.reduce((n,l)=>n+l.qty,0))} pieces)`).join('<br>')}</span>${r.imported?button('Confirm import','confirm-import','primary small'):''}</div>`;}
 catch(e){importPreview=null;$('#import-result').innerHTML=`<div class="notice refused"><span><b>Not imported.</b> ${esc(e.message)}</span></div>`;}}

/* ================================================================================
   Kitchen paperwork: printed on its own, never the screen around it
   ================================================================================ */
const printHead=(title,subtitle,right='')=>`<header class="print-head"><div><div class="eyebrow">${esc(state.settings.business||'Your bakery')}</div><h1>${esc(title)}</h1><p class="mini">${esc(subtitle)}</p></div><div style="text-align:right">${right}<p class="mini">Prepared ${esc(date(today()))}</p></div></header>`;
const printFoot=(text='')=>`<footer class="foot">${esc(text||'Bakeweek Studio · prepared from your current workspace.')}${demo?'<br>Made-up sample data. The recipes are costing examples, not tested recipes.':''}</footer>`;
function outShopping(p){const rows=p.shopping.filter(i=>i.required>0);
 return `<section class="sheet">${printHead('Shopping list',`Production week ${weekLabel(p.start)}`,`<b>${esc(cash(p.totals.shoppingCost))}</b>`)}<p class="mini">Batches still to make only. Pantry stock is subtracted and purchases round up to whole packs. Stock isn’t reserved for other weeks.</p>
 ${rows.length?`<table><thead><tr><th>Ingredient / supplier</th><th class="r">Need</th><th class="r">Pantry</th><th class="r">Short</th><th>Buy</th><th class="r">Est. spend</th></tr></thead><tbody>${rows.map(i=>`<tr><td><span class="box"></span><b>${esc(i.name)}</b>${i.supplier?`<br><span class="mini">${esc(i.supplier)}</span>`:''}</td><td class="r">${esc(qty(i.required,i.unit))}</td><td class="r">${esc(qty(i.stock,i.unit))}</td><td class="r">${esc(qty(i.shortfall,i.unit))}</td><td>${i.packs?`<b>${plural(i.packs,'pack')}</b><br><span class="mini">${esc(qty(i.packSize,i.unit))} each · ${esc(qty(i.buyQty,i.unit))}</span>`:'Covered'}</td><td class="r">${esc(i.packs?cash(i.cost):money(0))}</td></tr>`).join('')}</tbody></table>`:'<p>No ingredients to buy for this week.</p>'}
 <div class="line total"><span>Planned purchase cost</span><b>${esc(cash(p.totals.shoppingCost))}</b></div><p class="mini">Use Receive planned shopping in the app only after the listed packs arrive. Record partial or different purchases in Pantry.</p>${printFoot()}</section>`;}
function outRun(run,made){const r=recipe(run.recipeId),method=r?.method||'';
 return `<article class="blk"${method.length>1400?' style="break-inside:auto"':''}><div class="blk-head"><div><div class="eyebrow">${made?'Already made':'To make'} · ${esc(longDay(run.date))} ${esc(date(run.date))}</div><h2>${esc(run.recipeName)}</h2></div><div style="text-align:right"><b>${plural(run.batches,'batch','batches')}</b><p class="mini">${num(run.produced)} made · ${num(run.required)} for orders · ${num(run.extra)} extra</p></div></div>
 <p class="mini">Hands-on ${esc(mins(run.activeMinutes))} · oven ${esc(mins(run.ovenMinutes))} (reference) · ingredients ${esc(cash(run.ingredientCost))}</p>
 <table><thead><tr><th>Scaled ingredient</th><th class="r">For this run</th></tr></thead><tbody>${run.ingredients.map(i=>`<tr><td><span class="box"></span>${esc(i.name)}</td><td class="r"><b>${esc(qty(i.qty,i.unit))}</b></td></tr>`).join('')}</tbody></table>
 ${method?`<h3>Method</h3><div class="method">${esc(method)}</div>`:''}
 <h3>Allocate to these orders</h3><table><thead><tr><th>Order / customer</th><th>Pickup</th><th class="r">Pieces</th></tr></thead><tbody>${run.allocations.map(a=>{const o=order(a.orderId);return `<tr><td>${esc(o?.reference||'')} · ${esc(o?.customer||'Order')}</td><td>${esc(o?date(o.dueDate):'')}</td><td class="r">${num(a.qty)}</td></tr>`;}).join('')}</tbody></table>
 ${run.allocations.map(a=>order(a.orderId)).filter((o,i,l)=>o&&o.kitchenNote&&l.findIndex(x=>x?.id===o.id)===i).map(o=>`<p class="mini" style="white-space:pre-wrap"><b>${esc(o.reference)} kitchen note:</b> ${esc(o.kitchenNote)}</p>`).join('')}
 <p class="mini">${made?'Recorded as made: its ingredients were taken from the pantry then.':'When it’s done, choose Mark batch made in the app to take its ingredients from the pantry once.'}${run.extra?` ${num(run.extra)} extra pieces aren’t assigned to an order.`:''}</p></article>`;}
function outBatches(p){const runs=[...p.runs.map(run=>({run,made:false})),...p.completedRuns.map(run=>({run,made:true}))].sort((a,b)=>a.run.date.localeCompare(b.run.date)||a.run.recipeName.localeCompare(b.run.recipeName));
 return `<section class="sheet">${printHead('Batch sheets',`Production week ${weekLabel(p.start)}`,`<b>${plural(p.totals.batches,'batch','batches')}</b>`)}<p class="mini">Amounts are for each whole production run. Finishing and packing are listed by order on the packing tickets.</p>${runs.length?runs.map(x=>outRun(x.run,x.made)).join(''):'<p>No batches this week.</p>'}${printFoot()}</section>`;}
function outPacking(p){const os=p.orders.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.customer.localeCompare(b.customer));
 return `<section class="sheet">${printHead('Pack & collect',`Pickups ${weekLabel(p.start)}`,`<b>${plural(os.length,'pickup')}</b>`)}<p class="mini">Kitchen tickets: check what the customer asked for, finish the work and update the status in the app.</p>
 ${os.length?os.map(o=>`<article class="blk"><div class="blk-head"><div><div class="eyebrow">${esc(o.reference)} · ${esc(statusLabel(o.status))}</div><h2>${esc(o.customer)}</h2>${o.contact?`<p class="mini">${esc(o.contact)}</p>`:''}</div><div style="text-align:right"><b>Pickup ${esc(longDay(o.dueDate))} ${esc(date(o.dueDate))}</b><p class="mini">Bake ${esc(date(o.bakeDate))} · finish ${esc(date(o.finishDate))}</p></div></div>
  <table><thead><tr><th>Pack each item</th><th class="r">Pieces</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td><span class="box"></span>${esc(recipe(l.recipeId)?.name||'Product')}</td><td class="r"><b>${num(l.qty)}</b></td></tr>`).join('')}</tbody></table>
  ${o.customerNote?`<p style="white-space:pre-wrap"><b>Customer note:</b> ${esc(o.customerNote)}</p>`:''}${o.kitchenNote?`<p style="white-space:pre-wrap"><b>Kitchen note:</b> ${esc(o.kitchenNote)}</p>`:''}
  <p class="mini">Finishing and setup: about ${esc(mins(o.setupMinutes+o.lines.reduce((n,l)=>n+l.qty*l.finishMinutes,0)))}</p><div class="line"><span>Quoted / paid so far</span><b>${esc(money(rev(o)))} / ${esc(money(o.paid))}</b></div><div class="line total"><span>Balance due</span><b>${esc(money(balance(o)))}</b></div>
  <p class="mini"><span class="box"></span>Finished &amp; packed &nbsp; <span class="box"></span>Balance recorded &nbsp; <span class="box"></span>Collected</p></article>`).join(''):'<p>No pickups this week.</p>'}${printFoot()}</section>`;}
// the customer's copy uses only agreed prices, payments and customer notes: never costs or kitchen notes
function outQuote(id){const o=order(id);if(!o)throw Error('Open a saved order before printing its quote.');const total=rev(o);
 return `<section class="sheet">${printHead('Order quote',`Prepared for ${o.customer}`,`<b>${esc(o.reference)}</b>`)}<div class="cols"><div><h3>Customer</h3><p>${esc(o.customer)}${o.contact?`<br>${esc(o.contact)}`:''}</p></div><div><h3>Pickup</h3><p>${esc(longDay(o.dueDate))} ${esc(date(o.dueDate))}, ${o.dueDate.slice(0,4)}</p></div></div>
 <table><thead><tr><th>Item</th><th class="r">Pieces</th><th class="r">Price each</th><th class="r">Amount</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td>${esc(recipe(l.recipeId)?.name||'Product')}</td><td class="r">${num(l.qty)}</td><td class="r">${esc(money(l.unitPrice))}</td><td class="r">${esc(money(l.qty*l.unitPrice))}</td></tr>`).join('')}</tbody></table>
 <div style="max-width:320px;margin-left:auto"><div class="line"><span>Subtotal</span><b>${esc(money(total))}</b></div><div class="line"><span>Paid so far</span><b>${esc(money(o.paid))}</b></div><div class="line total"><span>Balance due</span><b>${esc(money(balance(o)))}</b></div></div>
 <p class="mini">All amounts in ${esc(state.settings.currency)}. Tax isn’t calculated on this quote.</p>${o.customerNote?`<h3>Order notes</h3><div class="method">${esc(o.customerNote)}</div>`:''}${printFoot('Thank you for supporting '+(state.settings.business||'our bakery')+'.')}</section>`;}
function printOut(kind,id){try{const p=plan(),html=kind==='quote'?outQuote(id):kind==='packet'?outShopping(p)+outBatches(p)+outPacking(p):kind==='shopping'?outShopping(p):kind==='batches'?outBatches(p):kind==='packing'?outPacking(p):'';
 if(!html)return print();closeModal();$('#print-area').innerHTML=html;document.body.classList.add('printing');
 requestAnimationFrame(()=>requestAnimationFrame(()=>{try{print();}catch{document.body.classList.remove('printing');toast('Printing couldn’t open. Try again in Chrome or Edge on a computer.');}}));}catch(e){toast(e.message);}}
window.addEventListener('afterprint',()=>document.body.classList.remove('printing'));
function shoppingText(){const p=plan(),short=p.shopping.filter(i=>i.packs>0).sort((a,b)=>(a.supplier||'').localeCompare(b.supplier||'')||a.name.localeCompare(b.name));
 const lines=[state.settings.business||'Your bakery','BAKEWEEK SHOPPING LIST',`Production week: ${weekLabel(p.start)}`,''];if(!short.length)lines.push('Nothing to buy for the batches still to make.');
 for(const i of short)lines.push(`[ ] ${i.name}`,`    Buy ${plural(i.packs,'pack')} x ${qty(i.packSize,i.unit)} = ${qty(i.buyQty,i.unit)}`,`    Need ${qty(i.required,i.unit)} | Pantry ${qty(i.stock,i.unit)} | Short ${qty(i.shortfall,i.unit)}`,`    Supplier: ${i.supplier||'Not entered'} | Estimated spend: ${cash(i.cost)}`,'');
 lines.push(`Planned purchase cost: ${cash(p.totals.shoppingCost)}`,'','Purchases round up to whole packs. Missing prices make the estimate incomplete.','Use Receive planned shopping only after every listed pack arrives.','Generated by Bakeweek Studio.');if(demo)lines.push('Made-up sample data.');
 download(`Bakeweek_Shopping_${week}.txt`,lines.join('\r\n')+'\r\n','text/plain;charset=utf-8');toast('Shopping list downloaded. Receive purchases only when they arrive.');}
// quote every CSV field and neutralize spreadsheet formulas in text the user typed
const csvCell=v=>{let t=String(v??'');if(typeof v!=='number'&&(/^\s*[=+\-@]/.test(t)||/^[\t\r\n]/.test(t)))t="'"+t;return '"'+t.replace(/"/g,'""')+'"';};
function exportOrders(){const rows=[['Order','Customer','Product','Quantity','Unit price','Pickup date','Bake date','Finish date','Finish minutes','Paid','Payment','Notes']];
 for(const o of state.orders.filter(o=>o.status!=='Cancelled').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.reference.localeCompare(b.reference)))for(const l of o.lines)rows.push([o.reference,o.customer,recipe(l.recipeId)?.name||l.recipeId,l.qty,l.unitPrice,o.dueDate,o.bakeDate,o.finishDate,l.finishMinutes,o.paid,o.payment,o.customerNote||'']);
 download(`Bakeweek_Orders_${today()}.csv`,'﻿'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')+'\r\n','text/csv;charset=utf-8');toast(`${plural(rows.length-1,'order line')} exported. A CSV isn’t a backup: use Download backup for that.`);}

/* ================================================================================
   Events: one delegated handler per event type
   ================================================================================ */
function go(id){screen=id;document.body.classList.remove('menu-open');render();scrollTo({top:0});$('#content').focus({preventScroll:true});}
const setWeek=w=>{week=C.monday(w);selectedDay='';render();};
const ACTIONS={
 go:b=>{go(b.dataset.go);if(b.dataset.anchor)setTimeout(()=>document.getElementById(b.dataset.anchor)?.scrollIntoView({block:'start'}),50);},menu:()=>document.body.classList.toggle('menu-open'),
 'rail-toggle':()=>{railMin=!railMin;ls.set(RAIL_KEY,railMin?'1':'0');applyRail();},
 'prev-week':()=>setWeek(C.addDays(week,-7)),'next-week':()=>setWeek(C.addDays(week,7)),'this-week':()=>setWeek(today()),
 'year-shift':b=>setWeek(C.addDays(week,364*+b.dataset.d)),
 'select-day':b=>{selectedDay=b.dataset.date;if(screen!=='week')screen='week';render();},
 pulse:b=>showPulse(+$('#pulse').dataset.at+ +b.dataset.d),'pulse-to':b=>showPulse(+b.dataset.i),
 page:b=>{UI[screen].page+=+b.dataset.d;render();},'status-filter':b=>{UI.orders.status=b.dataset.k;UI.orders.page=0;render();},
 'ask-ok':()=>{const f=askFn;askFn=null;closeModal();f?.();},dismiss:closeModal,
 undo:()=>{if(!undoState)return;state=undoState.state;prefs=undoState.prefs;undoState=null;save();render();toast('Undone');},
 sample:()=>{closeModal();toggleSample();},backup,restore:()=>$('#restore-file').click(),recovery:()=>download('Bakeweek_Recovery_Data.txt',recoveryRaw,'text/plain'),reload:()=>location.reload(),
 'choose-folder':chooseFolder,'reconnect-folder':reconnectFolder,'banner-hide':()=>{bannerHidden=true;renderStatus();},
 theme:b=>commit((s,p)=>{p.theme=b.dataset.k;},'Palette changed'),
 fresh:()=>ask('Start fresh?','This clears every ingredient, recipe, order and batch record. Download a backup first if you may need it. You can undo straight after.','Start fresh',()=>commit(s=>{for(const k of Object.keys(s))delete s[k];Object.assign(s,C.createBlank());},'Started fresh')),
 tour:()=>openTour(false),'tour-step':b=>{tourAt+=+b.dataset.d;renderTour();$('#welcome [autofocus]')?.focus();},'tour-close':closeTour,'tour-sample':()=>{closeTour();if(!demo)toggleSample();},
 print:b=>printOut(b.dataset.k,b.dataset.id),'shopping-text':shoppingText,'export-orders':exportOrders,
 'ingredient-form':b=>ingredientForm(b.dataset.id),'recipe-form':b=>recipeForm(b.dataset.id),'order-form':b=>orderForm(b.dataset.id),simulator,
 capacity:capacityForm,payment:b=>paymentForm(b.dataset.id),'receive-ingredient':b=>receiveForm(b.dataset.id),'import-orders':importForm,
 'csv-template':()=>download('Bakeweek_Order_Import_Template.csv',C.orderCSVTemplate(state),'text/csv'),'csv-file':()=>$('#csv-file').click(),'preview-import':previewImport,
 'confirm-import':()=>{if(!importPreview||$('[name=csvText]').value!==importPreview.text)return toast('Preview the current CSV first.');const r=commit(s=>C.importOrders(s,importPreview.text),'Orders imported');if(r.ok){closeModal();go('orders');}},
 'add-recipe-ingredient':()=>{const used=new Set(recipeRows.map(l=>l.ingredientId)),i=state.ingredients.find(i=>!i.archived&&!used.has(i.id));if(!i)return formError('Every pantry ingredient is already in this recipe.');recipeRows.push({ingredientId:i.id,qty:100});$('#recipe-rows').innerHTML=ingRows();},
 'remove-recipe-ingredient':b=>{if(recipeRows.length===1)return formError('Keep at least one ingredient in the recipe.');recipeRows.splice(+b.dataset.index,1);$('#recipe-rows').innerHTML=ingRows();},
 'add-line':b=>lineEdit(b,'add'),'remove-line':b=>lineEdit(b,'remove'),
 'sim-simple':()=>{simDraft.lines.forEach(l=>l.finishMinutes=2);updateSimFields();},'sim-default':()=>{simDraft.lines.forEach(l=>l.finishMinutes=recipe(l.recipeId).finishMinutes);updateSimFields();},
 'sim-price':()=>{if(!simResult||suggestedQuote(simResult)===null)return toast('Add ingredient prices for every planned batch and this draft first.');const q=simResult.quote,target=Math.max(q.revenue,suggestedQuote(simResult)),total=simDraft.lines.reduce((n,l)=>n+l.qty,0);simDraft.lines.forEach(l=>l.unitPrice=Math.ceil((q.revenue?l.unitPrice*target/q.revenue:target/total)*100)/100);updateSimFields();},
 'sim-days':()=>{let best=null;for(let d=simDraft.bakeDate;d<=C.addDays(week,6)&&d<=simDraft.dueDate;d=C.addDays(d,1))for(let f=d;f<=C.addDays(week,6)&&f<=simDraft.dueDate;f=C.addDays(f,1)){try{const c={...simDraft,bakeDate:d,finishDate:f},r=C.simulateOrder(state,c,week),score=r.after.totals.overMinutes;if(!best||score<best.score)best={c,score};}catch{}}
  if(!best)return toast('Use valid dates in this week to try alternatives.');simDraft=best.c;updateSimFields();toast(best.score?'That’s the least overloaded option from the bake date on.':'These dates fit your hours. Review them before accepting.');},
 'accept-sim':()=>{if(!$('#sim-form').reportValidity()||!simResult)return;const r=commit(s=>C.addOrder(s,simDraft),'Order accepted. The plan, shopping and packing are ready.');if(r.ok){closeModal();selectedDay=simDraft.finishDate;go('week');}},
 'recipe-status':b=>{UI.recipes.status=b.dataset.k;render();},'recipe-view':b=>commit((s,p)=>{p.recipeView=b.dataset.k;}),
 'recipe-pic-remove':()=>{recipeImg=null;$('#recipe-pic').innerHTML=imgBox('',$('#recipe-form [name=color]').value);},
 'cat-move':b=>{const i=+b.dataset.i,j=i+ +b.dataset.d;commit((s,p)=>{const l=catList();for(const c of l)p.categoryColors[c]=catColor(c);[l[i],l[j]]=[l[j],l[i]];p.categories=l;},'Category moved');},
 'cat-rename':b=>{const old=catList()[+b.dataset.i];modal('Rename category',`${esc(old)} · every recipe in it moves to the new name.`,`<form id="cat-form" data-old="${esc(old)}"><div class="fields">${fld('name','New name',old,{attrs:'required maxlength="80"',full:true})}</div>${formFoot('Rename')}</form>`);},
 'cat-delete':b=>{const c=catList()[+b.dataset.i],n=state.recipes.filter(r=>r.category===c).length;ask(`Delete “${esc(c)}”?`,n?`Its ${plural(n,'recipe')} become Uncategorized; nothing else changes. You can undo straight after.`:'It has no recipes. You can undo straight after.','Delete category',()=>commit((s,p)=>{for(const r of s.recipes.filter(r=>r.category===c))C.updateRecipe(s,r.id,{category:''});p.categories=catList().filter(x=>x!==c);delete p.categoryColors[c];},'Category deleted'));},
 'archive-recipe':b=>{const r=recipe(b.dataset.id);ask(r.archived?'Activate this recipe?':'Archive this recipe?',r.archived?'It becomes available for new orders again.':'Existing orders keep it; it’s hidden when you add new orders.',r.archived?'Activate':'Archive',()=>commit(s=>C.updateRecipe(s,r.id,{archived:!r.archived}),r.archived?'Recipe activated':'Recipe archived'),!r.archived);},
 'complete-run':b=>{const r=plan().runs.find(x=>x.key===b.dataset.key);if(!r)return;ask('Mark this batch made?',`This takes the ingredients for ${plural(r.batches,'batch','batches')} of ${esc(r.recipeName)} from your pantry and records ${num(r.required)} pieces for orders. You can undo it.`,'Mark made',()=>commit(s=>C.completeRun(s,b.dataset.key,week),'Batch recorded. Pantry stock updated.'),false);},
 'undo-run':b=>ask('Undo this batch?','Its exact ingredient amounts go back to the pantry and the work becomes pending again. Affected orders must be Confirmed.','Undo batch',()=>commit(s=>C.undoRun(s,b.dataset.id),'Batch undone. Ingredients restored.')),
 'receive-shopping':()=>{const n=plan().shopping.filter(x=>x.packs>0).length;if(!n)return toast('Nothing left to buy for this week.');ask('Receive planned shopping?',`This adds the recommended whole packs for ${plural(n,'ingredient')} to your pantry. Use it only after they’ve actually arrived.`,'Receive',()=>commit(s=>C.receiveShopping(s,week),'Planned shopping added to the pantry'),false);},
 'order-status':b=>{closeModal();commit(s=>C.setOrderStatus(s,b.dataset.id,b.dataset.status),`Order marked ${statusLabel(b.dataset.status).toLowerCase()}`);},
 'cancel-order':b=>ask('Cancel this order?','It leaves the plan, shopping and packing. The order stays in your order book, and you can undo this.','Cancel order',()=>commit(s=>C.setOrderStatus(s,b.dataset.id,'Cancelled'),'Order canceled')),
 'delete-order':b=>ask('Delete this order?','It’s removed from your order book and every plan. You can undo straight after.','Delete order',()=>commit(s=>C.deleteOrder(s,b.dataset.id),'Order deleted')),
};
function lineEdit(b,kind){const scope=b.dataset.scope,lines=scope==='sim'?simDraft.lines:orderRows;
 if(kind==='add'){const r=state.recipes.find(r=>!r.archived&&!lines.some(l=>l.recipeId===r.id));if(!r)return formError('Every active product is already in this order.');lines.push({recipeId:r.id,qty:12,unitPrice:r.unitPrice,finishMinutes:r.finishMinutes});}
 else{if(lines.length===1)return formError('Keep at least one product in the order.');lines.splice(+b.dataset.index,1);}
 $(scope==='sim'?'#sim-rows':'#order-rows').innerHTML=lineRows(lines,scope);if(scope==='sim')updateSimulation();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||b.tagName==='INPUT')return;const f=ACTIONS[b.dataset.action];if(!f)return;try{f(b);}catch(err){toast(err.message);}});
document.addEventListener('keydown',e=>{
 const el=e.target;if((e.key==='Enter'||e.key===' ')&&el.matches?.('[role=button][data-action]')&&!/BUTTON|A/.test(el.tagName)){e.preventDefault();el.click();return;}
 if(e.key==='Escape')document.body.classList.remove('menu-open');
 if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&!/INPUT|TEXTAREA|SELECT/.test(el.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();simulator();}});
document.addEventListener('input',e=>{const x=e.target;
 if(x.id==='search'&&UI[screen]){UI[screen].q=x.value;if('page' in UI[screen])UI[screen].page=0;clearTimeout(UI.t);UI.t=setTimeout(render,250);return;}
 if(x.dataset.sim&&simDraft){simDraft[x.dataset.sim]=['setupMinutes','extraCost'].includes(x.dataset.sim)?+x.value:x.value;updateSimulation();}
 if(x.dataset.line&&x.tagName!=='SELECT'){const lines=x.dataset.scope==='sim'?simDraft.lines:orderRows,i=+x.closest('[data-index]').dataset.index;lines[i][x.dataset.line]=x.value===''?NaN:+x.value;if(x.dataset.scope==='sim')updateSimulation();}
 if(x.dataset.ri==='qty')recipeRows[+x.closest('[data-index]').dataset.index].qty=+x.value;
 if(x.name==='csvText'){importPreview=null;$('#import-result').innerHTML='';}});
document.addEventListener('change',e=>{const x=e.target;
 if(x.dataset.catColor!==undefined){const c=catList()[+x.dataset.catColor];if(c)commit((s,p)=>{p.categoryColors[c]=x.value.toLowerCase();},'Color changed');return;}
 if(x.id==='recipe-cat'){UI.recipes.cat=x.value;render();}if(x.id==='recipe-sort'){UI.recipes.sort=x.value;render();}
 if(x.id==='recipe-pic-file'&&x.files[0]){readPicture(x.files[0]).then(d=>{recipeImg=d;$('#recipe-pic').innerHTML=imgBox(d,'');}).catch(err=>formError(err.message));x.value='';}
 if(x.dataset.sim==='payment'){simDraft.payment=x.value;updateSimulation();}
 if(x.dataset.line==='recipeId'){const lines=x.dataset.scope==='sim'?simDraft.lines:orderRows,i=+x.closest('[data-index]').dataset.index,r=recipe(x.value);lines[i]={...lines[i],recipeId:r.id,unitPrice:r.unitPrice,finishMinutes:r.finishMinutes};$(x.dataset.scope==='sim'?'#sim-rows':'#order-rows').innerHTML=lineRows(lines,x.dataset.scope);if(x.dataset.scope==='sim')updateSimulation();}
 if(x.dataset.ri==='ingredientId'){recipeRows[+x.closest('[data-index]').dataset.index].ingredientId=x.value;$('#recipe-rows').innerHTML=ingRows();}
 if(x.dataset.navToggle){const k=x.dataset.navToggle;commit((s,p)=>{const h=p.hiddenNav.filter(v=>v!==k);if(!x.checked)h.push(k);p.hiddenNav=h;},x.checked?'Shown in the sidebar':'Hidden from the sidebar');}
 if(x.id==='week-picker'&&/^\d{4}-\d{2}-\d{2}$/.test(x.value))setWeek(x.value);
 if(x.id==='restore-file'&&x.files[0]){const f=x.files[0];x.value='';readBackup(f).then(b=>ask('Restore this backup?',`${plural(b.data.orders.length,'order')}, ${plural(b.data.recipes.length,'recipe')} and ${plural(b.data.ingredients.length,'ingredient')} from ${esc(b.data.settings.business)}. It replaces your ${demo?'own ':''}bakery in this browser; you can undo straight after.`,'Restore',()=>restoreFrom(b),false)).catch(err=>toast(err.message));}
 if(x.id==='csv-file'&&x.files[0]){const f=x.files[0];x.value='';if(f.size>4*1024*1024)return toast('The CSV must be under 4 MB.');f.text().then(t=>{const a=$('[name=csvText]');if(a){a.value=t;previewImport();}}).catch(()=>toast('That CSV couldn’t be read.'));}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,id=f.dataset.id;
 if(f.id==='ingredient-form')formSave(f,(s,d)=>{d.packCost=d.packCost===''?null:d.packCost;return id?C.updateIngredient(s,id,d):C.addIngredient(s,d);},id?'Ingredient saved':'Ingredient added');
 if(f.id==='recipe-form')formSave(f,(s,d,p)=>{d.ingredients=recipeRows;const r=id?C.updateRecipe(s,id,d):C.addRecipe(s,d);if(recipeImg===null)delete p.images[r.id];else if(recipeImg)p.images[r.id]=recipeImg;return r;},id?'Recipe saved':'Recipe added');
 if(f.id==='order-form')formSave(f,(s,d)=>C.updateOrder(s,id,{...d,lines:orderRows}),'Order saved');
 if(f.id==='payment-form')formSave(f,(s,d)=>C.recordPayment(s,id,d.paid),'Payment recorded');
 if(f.id==='receive-form')formSave(f,(s,d)=>C.receiveIngredient(s,id,d.qty),'Stock added to the pantry');
 if(f.id==='settings-form'){if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));commit(s=>{s.settings={...s.settings,business:d.business,currency:d.currency,hourlyRate:+d.hourlyRate,targetMargin:+d.targetMargin,cardRate:+d.cardRate,fixedFee:+d.fixedFee};},'Settings saved');}
 if(f.id==='capacity-form'){if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));commit(s=>{s.settings.capacity=Array.from({length:7},(_,n)=>Math.round(+d['cap'+n]*60));},'Working hours saved');}
 if(f.id==='cat-add-form'){const name=new FormData(f).get('name').trim();if(!name)return;if(catList().some(c=>c.toLowerCase()===name.toLowerCase()))return toast('That category already exists.');const color=new FormData(f).get('color');commit((s,p)=>{p.categories=[...catList(),name];if(/^#[0-9a-f]{6}$/i.test(color))p.categoryColors[name]=color;},'Category added');}
 if(f.id==='cat-form'){const old=f.dataset.old,name=new FormData(f).get('name').trim();if(name!==old&&catList().some(c=>c.toLowerCase()===name.toLowerCase()))return formError('That category already exists.');formSave(f,(s,d,p)=>{for(const r of s.recipes.filter(r=>r.category===old))C.updateRecipe(s,r.id,{category:name});p.categories=catList().map(c=>c===old?name:c);if(name!==old){p.categoryColors[name]=catColor(old);delete p.categoryColors[old];}},'Category renamed');}
 if(f.id==='sim-form')ACTIONS['accept-sim']();});

/* ---------- start ---------- */
$$('[data-action="prev-week"]').forEach(b=>b.innerHTML=ico('left'));$$('[data-action="next-week"]').forEach(b=>b.innerHTML=ico('right'));
$('.mobile-menu').innerHTML=ico('menu');$('.topbar [data-go="guide"]').innerHTML=ico('help')+'<span>Guide</span>';$('.topbar [data-action="backup"]').innerHTML=ico('down')+'<span>Back up</span>';
$('#rail-note').innerHTML=CONFIG.railNote;$('#rail-version').textContent=`${CONFIG.tagline} · v${CONFIG.version}`;
Promise.all([load(),initFolder()]).then(()=>{if(new URLSearchParams(location.search).get('demo')==='1')toggleSample(true);render();startupPrompt();});
