import { createRequire } from 'module'; import path from 'path';
const require = createRequire('/opt/node22/lib/node_modules/playwright/package.json'); const { chromium } = require('playwright');
const here = path.dirname(new URL(import.meta.url).pathname); const file = 'file://' + path.resolve(here, '..', 'Personal_Finance_Dashboard.html');
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1380, height: 900 } });
await page.goto(file); await page.waitForSelector('#wizBody');
await page.click('#wizNext'); await page.click('#wizNext'); await page.waitForTimeout(100);
await page.screenshot({ path: path.join(here, 'shots', '40-wizard-theme.png') });
await page.click('.theme-card[data-wiz-theme=sage]'); await page.waitForTimeout(100);
await page.click('#wizNext'); await page.click('label:has(input[name=data][value=sample])'); await page.click('#wizNext'); await page.waitForTimeout(300);
await page.screenshot({ path: path.join(here, 'shots', '41-tour-1.png') });
await page.click('#tourNext'); await page.waitForTimeout(100); await page.screenshot({ path: path.join(here, 'shots', '42-tour-2.png') });
await page.click('#tourSkip'); await page.waitForTimeout(200);
await page.screenshot({ path: path.join(here, 'shots', '43-sage-overview.png') });
await page.click('[data-action=quickAdd]'); await page.waitForTimeout(100); await page.screenshot({ path: path.join(here, 'shots', '44-quickadd.png') });
await page.click('.qa[data-qa=txnAdd]'); await page.waitForTimeout(100); await page.screenshot({ path: path.join(here, 'shots', '45-txn-form.png') });
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(200); await page.screenshot({ path: path.join(here, 'shots', '46-mobile-sage.png'), fullPage: false });
await browser.close();
