// Unit tests on what ships: BakeCore is read out of the built Bakeweek_Studio.html, not src/.
//   node test.js
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {build}=require('./build.js');
let pass=0,fail=0;const t=(name,fn)=>{try{fn();pass++;}catch(e){fail++;console.log('FAIL',name,'\n  ',e.message);}};
const html=fs.readFileSync(__dirname+'/Bakeweek_Studio.html','utf8');
t('built file is current',()=>assert.strictEqual(html,build(),'run: node build.js'));
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const ctx={};vm.createContext(ctx);vm.runInContext(scripts[0],ctx);const C=ctx.BakeCore;
t('BakeCore loads from the built file',()=>assert.ok(C&&C.planWeek));
const W='2026-10-05',demo=()=>C.createDemo('2026-10-06');
t('demo week totals',()=>{const p=C.planWeek(demo(),W).totals;assert.strictEqual(p.orders,9);assert.strictEqual(p.pendingBatches,15);assert.strictEqual(p.activeMinutes,842);assert.ok(Math.abs(p.shoppingCost-69.2)<1e-6);assert.ok(Math.abs(p.quotedRevenue-734.4)<1e-6);assert.ok(Math.abs(p.balanceDue-373.8)<1e-6);});
t('whole batches and extras',()=>{const r=C.planWeek(demo(),W).runs.find(r=>r.recipeName==='Signature chocolate cookies'&&r.date==='2026-10-08');assert.strictEqual(r.batches,4);assert.strictEqual(r.produced,48);assert.strictEqual(r.extra,6);});
t('shopping rounds up to whole packs',()=>{const b=C.planWeek(demo(),W).shopping.find(i=>i.name==='Butter');assert.strictEqual(b.packs,4);assert.strictEqual(b.buyQty,2000);});
t('complete a batch takes stock once; undo restores it',()=>{const s=demo(),key=C.planWeek(s,W).runs[0].key,before=s.ingredients.find(i=>i.id==='flour').stock;C.receiveShopping(s,W);const afterRx=s.ingredients.find(i=>i.id==='flour').stock;const run=C.completeRun(s,key,W);assert.ok(s.ingredients.find(i=>i.id==='flour').stock<afterRx);assert.throws(()=>C.completeRun(s,key,W));C.undoRun(s,run.id);assert.strictEqual(s.ingredients.find(i=>i.id==='flour').stock,afterRx);assert.ok(afterRx>before);});
t('not enough stock is refused',()=>{const s=demo(),key=C.planWeek(s,W).runs.find(r=>r.batches>=4).key;assert.throws(()=>C.completeRun(s,key,W),/Not enough/);});
t('ready needs every batch made; collected needs ready',()=>{const s=demo(),o=s.orders[0];assert.throws(()=>C.setOrderStatus(s,o.id,'Ready'),/Complete every batch/);assert.throws(()=>C.setOrderStatus(s,o.id,'Collected'),/ready/);});
t('try an order: overload found, nothing saved',()=>{const s=demo(),n=s.orders.length,r=C.simulateOrder(s,{reference:'X-1',customer:'Test',dueDate:'2026-10-10',bakeDate:'2026-10-08',finishDate:'2026-10-09',payment:'Card',paid:0,setupMinutes:15,extraCost:0,lines:[{recipeId:'cookie',qty:48,unitPrice:3.8,finishMinutes:6}]},W);assert.strictEqual(r.fits,false);assert.strictEqual(s.orders.length,n);assert.ok(r.quote.minPriceAtTarget>0);});
t('payments cannot exceed the order',()=>{const s=demo();assert.throws(()=>C.recordPayment(s,s.orders[0].id,1e6));});
t('CSV import: template round trip and duplicate skip',()=>{const s=demo(),csv=C.orderCSVTemplate(s).replace('ORDER-001','NEW-1');const r=C.importOrders(s,csv);assert.strictEqual(r.imported,1);const r2=C.importOrders(s,csv);assert.strictEqual(r2.imported,0);assert.strictEqual(r2.skipped,1);});
t('CSV import refuses wrong headers',()=>assert.throws(()=>C.importOrders(demo(),'a,b\n1,2'),/headers/));
t('backups: Codex-format data validates; other files are refused',()=>{const s=demo();assert.ok(C.validateBackup(JSON.parse(JSON.stringify({...s,ui:{theme:'kiln'},app:'jps-bakeweek'}))));assert.throws(()=>C.validateBackup({schema:'x',version:1}),/not a supported/);});
const same=(a,b)=>assert.strictEqual(JSON.stringify(a),JSON.stringify(b));
// standing orders and market days
const SOD={customer:'Corner Café',type:'Wholesale',lines:[{recipeId:'cookie',qty:24}],days:['1','4'],every:'1',start:'2026-10-05',end:'',bakeLead:'1',finishLead:'0',payment:'Other',setupMinutes:'5'};
t('standing: drops on its days, every N weeks, nothing twice',()=>{const s=demo();C.saveStanding(s,SOD,'2026-10-06');const so=s.standing[0];assert.strictEqual(so.code,'ST1');
 same(C.standingDates(so,'2026-10-06','2026-10-18'),['2026-10-06','2026-10-09','2026-10-13','2026-10-16']);assert.strictEqual(C.syncStanding(s,'2026-10-06','2026-10-18').created,4);assert.strictEqual(C.syncStanding(s,'2026-10-06','2026-10-18').created,0);
 const o=s.orders.find(o=>o.standingId&&o.dueDate==='2026-10-09');assert.strictEqual(o.bakeDate,'2026-10-08');assert.strictEqual(o.reference,'ST1-261009');
 C.saveStanding(s,{...so,every:2},'2026-10-06');C.syncStanding(s,'2026-10-06','2026-10-18');same(s.orders.filter(o=>o.standingId).map(o=>o.dueDate).sort(),['2026-10-06','2026-10-09']);});
t('standing: a deleted drop is a skipped week; a canceled one stays canceled',()=>{const s=demo();C.saveStanding(s,SOD,'2026-10-06');C.syncStanding(s,'2026-10-06','2026-10-18');const a=s.orders.find(o=>o.dueDate==='2026-10-06'&&o.standingId),b=s.orders.find(o=>o.dueDate==='2026-10-09'&&o.standingId);
 C.deleteOrder(s,a.id);C.setOrderStatus(s,b.id,'Cancelled');assert.strictEqual(C.syncStanding(s,'2026-10-06','2026-10-18').created,0);same(s.standing[0].skips,['2026-10-06']);});
t('standing: prepaid drops are paid; paused makes none; edits keep touched drops',()=>{const s=demo();C.saveStanding(s,{...SOD,prepaid:true},'2026-10-06');C.syncStanding(s,'2026-10-06','2026-10-11');assert.ok(s.orders.filter(o=>o.standingId).every(o=>Math.abs(o.paid-91.2)<1e-6));
 const so=s.standing[0],keep=s.orders.find(o=>o.standingId);C.setOrderStatus(s,keep.id,'Cancelled');C.saveStanding(s,{...so,paused:true,prepaid:false},'2026-10-06');same(s.orders.filter(o=>o.standingId).map(o=>o.id),[keep.id]);assert.strictEqual(C.missingStanding(s,'2026-10-06','2026-11-30').length,0);});
t('standing: bad input refused',()=>{const s=demo();assert.throws(()=>C.saveStanding(s,{...SOD,days:[]},'2026-10-06'),/at least one day/);assert.throws(()=>C.saveStanding(s,{...SOD,bakeLead:'0',finishLead:'1'},'2026-10-06'),/Finishing/);assert.throws(()=>C.saveStanding(s,{...SOD,end:'2026-01-01'},'2026-10-06'),/end date/);});
const market=s=>C.addOrder(s,{kind:'market',reference:'MK-1',customer:'Saturday market',dueDate:'2026-10-10',bakeDate:'2026-10-09',finishDate:'2026-10-10',payment:'Cash',lines:[{recipeId:'shortbread',qty:24},{recipeId:'brownie',qty:16}],market:{stallFee:35}});
t('market: in the plan as stock, not as a customer balance',()=>{const s=demo(),before=C.planWeek(s,W).totals;market(s);const p=C.planWeek(s,W).totals;assert.strictEqual(p.markets,1);assert.ok(Math.abs(p.marketValue-118.4)<1e-6);assert.strictEqual(p.orders,before.orders);assert.ok(Math.abs(p.balanceDue-before.balanceDue)<1e-6);assert.ok(p.batches>before.batches);});
t('market: close needs made batches; results give takings, leftovers and waste',()=>{const s=demo();for(const i of s.ingredients)i.stock+=1e5;const m=market(s);assert.throws(()=>C.closeMarket(s,m.id,[]),/Ready/);assert.throws(()=>C.setOrderStatus(s,m.id,'Collected'));
 for(const r of C.planWeek(s,W).runs.filter(r=>r.allocations.some(a=>a.orderId===m.id)))C.completeRun(s,r.key,W);C.setOrderStatus(s,m.id,'Ready');assert.throws(()=>C.closeMarket(s,m.id,[{recipeId:'shortbread',sold:30,fate:'wasted'},{recipeId:'brownie',sold:1,fate:'wasted'}]));
 C.closeMarket(s,m.id,[{recipeId:'shortbread',sold:20,fate:'discounted',reducedTakings:4},{recipeId:'brownie',sold:12,fate:'wasted'}]);const o=s.orders.find(x=>x.id===m.id),r=C.marketResult(s,o);
 assert.strictEqual(o.status,'Collected');assert.strictEqual(r.sold,32);assert.strictEqual(r.leftover,8);assert.ok(Math.abs(r.takings-(20*2.6+12*3.5+4))<1e-6);assert.strictEqual(r.byFate.wasted,4);assert.ok(Math.abs(r.sellThrough-0.8)<1e-9);assert.ok(r.lostValue>0);
 const sg=C.marketSuggestion(s,'saturday MARKET','brownie','2026-12-01');assert.strictEqual(sg.suggest,Math.ceil(12*1.05));const so=C.marketSuggestion(s,'Saturday market','shortbread','2026-12-01');assert.strictEqual(so.soldOut,0);
 C.setOrderStatus(s,m.id,'Ready');assert.strictEqual(s.orders.find(x=>x.id===m.id).market.closed,false);});
// dough prep the day before, and the weekly pre-order menu
t('prep: lands on the day before, counts toward that day, and reaches back from next week',()=>{const s=demo();C.updateRecipe(s,'cookie',{prepDays:1,prepMinutes:10,prepNote:'Chill dough'});const p=C.planWeek(s,W),runs=p.runs.filter(r=>r.recipeId==='cookie');
 for(const r of runs){const d=p.days.find(x=>x.date===C.addDays(r.date,-1));assert.ok(d.preps.some(x=>x.bakeDate===r.date&&x.minutes===r.batches*10&&x.note==='Chill dough'));}
 assert.strictEqual(p.totals.prepMinutes,runs.reduce((n,r)=>n+r.batches*10,0));assert.strictEqual(p.totals.activeMinutes,842+p.totals.prepMinutes);
 C.addOrder(s,{reference:'MON-1',customer:'Early',dueDate:'2026-10-12',bakeDate:'2026-10-12',finishDate:'2026-10-12',payment:'Cash',lines:[{recipeId:'cookie',qty:12}]});assert.ok(C.planWeek(s,W).days[6].preps.some(x=>x.bakeDate==='2026-10-12'));
 assert.throws(()=>C.updateRecipe(s,'cookie',{prepDays:5}),/prep/i);});
const MENU={week:'2026-10-07',days:['2026-10-09'],cutoffDate:'2026-10-07',cutoffTime:'20:00',bakeLead:'1',items:[{recipeId:'cookie',unitPrice:'3.5',limit:'24'},{recipeId:'brownie',limit:''}]};
t('menu: one a week, limits enforced, orders go into the plan',()=>{const s=demo(),m=C.saveMenu(s,MENU);assert.strictEqual(m.week,W);assert.throws(()=>C.saveMenu(s,MENU),/already has a menu/);
 const o=C.addMenuOrder(s,m.id,{customer:'Sam',dueDate:'2026-10-09',qty:{cookie:20,brownie:2},paid:'10',payment:'Card'});assert.strictEqual(o.menuId,m.id);assert.strictEqual(o.bakeDate,'2026-10-08');assert.strictEqual(o.lines[0].unitPrice,3.5);
 assert.throws(()=>C.addMenuOrder(s,m.id,{customer:'X',dueDate:'2026-10-09',qty:{cookie:5}}),/Only 4/);assert.throws(()=>C.addMenuOrder(s,m.id,{customer:'X',dueDate:'2026-10-10',qty:{cookie:1}}),/pickup days/);assert.throws(()=>C.addMenuOrder(s,m.id,{customer:'X',dueDate:'2026-10-09',qty:{}}),/at least one/);
 assert.ok(C.planWeek(s,W).orders.some(x=>x.id===o.id));const t=C.menuTally(s,m);assert.strictEqual(t[0].left,4);assert.strictEqual(t[1].left,null);C.setOrderStatus(s,o.id,'Cancelled');assert.strictEqual(C.menuTally(s,m)[0].left,24);});
t('menu: bad input refused',()=>{const s=demo();assert.throws(()=>C.saveMenu(s,{...MENU,days:[]}),/pickup day/);assert.throws(()=>C.saveMenu(s,{...MENU,days:['2026-10-20']}),/week/);assert.throws(()=>C.saveMenu(s,{...MENU,cutoffDate:'2026-10-10'}),/close/);assert.throws(()=>C.saveMenu(s,{...MENU,cutoffTime:'25:00'}),/time/);assert.throws(()=>C.saveMenu(s,{...MENU,items:[]}),/at least one product/);});
// labels, customers, expenses, pantry minimums
t('labels: ingredients heaviest first, allergens from the pantry, the baker’s own list wins',()=>{const s=demo();C.updateIngredient(s,'flour',{allergens:['wheat'],labelName:'wheat flour'});C.updateIngredient(s,'butter',{allergens:['milk']});C.updateIngredient(s,'eggs',{allergens:['eggs','eggs']});
 const L=C.labelInfo(s,s.recipes.find(r=>r.id==='cookie'));same(L.allergens,['wheat','milk','eggs']);assert.ok(L.ingredients.startsWith('wheat flour, Chocolate chips, Brown sugar, Butter, Eggs'));
 C.updateRecipe(s,'cookie',{labelText:'flour, love',keepsDays:'5',pieceWeight:'70'});const r=s.recipes.find(r=>r.id==='cookie');assert.strictEqual(C.labelInfo(s,r).ingredients,'flour, love');assert.strictEqual(r.keepsDays,5);
 assert.throws(()=>C.updateIngredient(s,'flour',{allergens:['gluten']}),/Allergen/);});
t('customers: one card per name, allergies kept; expenses validated',()=>{const s=demo();const a=C.saveCustomer(s,{name:'Maya',allergies:'Tree nuts'}),b=C.saveCustomer(s,{name:'MAYA ',notes:'Pink'});assert.strictEqual(a.id,b.id);assert.strictEqual(s.customers.length,1);assert.strictEqual(s.customers[0].allergies,'Tree nuts');
 const e=C.saveExpense(s,{date:'2026-10-01',category:'Packaging',description:'Bags',amount:'42.5'});assert.strictEqual(e.amount,42.5);C.saveExpense(s,{...e,amount:'40'});assert.strictEqual(s.expenses[0].amount,40);
 assert.throws(()=>C.saveExpense(s,{date:'2026-10-01',category:'Snacks',amount:'5'}),/category/);assert.throws(()=>C.saveExpense(s,{date:'2026-10-01',category:'Other',amount:'0'}));C.deleteExpense(s,e.id);assert.strictEqual(s.expenses.length,0);});
t('settings and pantry: label details and minimums survive a backup round trip',()=>{const s=demo();s.settings.address='14 Elm St';s.settings.labelFooter='Home kitchen.';C.updateIngredient(s,'flour',{minStock:'5000'});const b=C.validateBackup(JSON.parse(JSON.stringify(s)));assert.strictEqual(b.settings.labelFooter,'Home kitchen.');assert.strictEqual(b.ingredients.find(i=>i.id==='flour').minStock,5000);});
t('routines: on their weekdays, counted toward the day, ticked off per date',()=>{const s=demo(),r=C.saveRoutine(s,{name:'Feed starter',days:['1','3'],minutes:'15'});const p=C.planWeek(s,W);assert.strictEqual(p.days[1].routineMinutes,15);assert.strictEqual(p.days[0].routines.length,0);assert.strictEqual(p.totals.routineMinutes,30);assert.strictEqual(p.totals.activeMinutes,842+30);
 assert.strictEqual(C.toggleRoutine(s,r.id,'2026-10-06'),true);assert.ok(C.planWeek(s,W).days[1].routines[0].done);assert.strictEqual(C.toggleRoutine(s,r.id,'2026-10-06'),false);C.toggleRoutine(s,r.id,'2026-10-08');C.deleteRoutine(s,r.id);assert.strictEqual(s.routineLog.length,0);assert.throws(()=>C.saveRoutine(s,{name:'X',days:[]}),/at least one day/);});
// the sample bakery (UI layer) must be valid data too
const ui=scripts[1],f=ui.slice(ui.indexOf('function sampleBakery'),ui.indexOf('/* ---------- recipe categories'));
const sb=new Function('C','today',f+'\nreturn sampleBakery();')(C,()=>'2026-10-06');
t('sample bakery: history validates',()=>{assert.ok(C.validateBackup(sb));assert.ok(sb.orders.length>250);assert.strictEqual(sb.standing.length,6);});
t('sample bakery: the past is collected, paid, made and closed',()=>{const past=sb.orders.filter(o=>o.dueDate<'2026-10-05'&&o.status!=='Cancelled');assert.ok(past.every(o=>o.status==='Collected'&&o.snapshot&&(o.kind==='market'?o.market.closed:Math.abs(o.paid-o.snapshot.revenue)<1e-6)));});
t('sample bakery: this week has drops, custom orders and a planned market',()=>{const p=C.planWeek(sb,W),t=p.totals;assert.strictEqual(t.markets,1);assert.ok(p.orders.some(o=>o.standingId)&&p.orders.some(o=>!o.standingId&&o.kind==='order'));assert.strictEqual(t.completedBatches,0);assert.strictEqual(C.missingStanding(sb,'2026-10-06','2026-11-01').length,0);});
t('sample bakery: market suggestions come from its history',()=>{const s=C.marketSuggestion(sb,'Saturday farmers market','country','2026-10-10');assert.ok(s&&s.markets===4&&s.suggest>10);});
t('sample bakery: weekly menus with pre-orders inside their limits, and prep the day before',()=>{assert.strictEqual(sb.menus.length,13);for(const m of sb.menus)for(const x of C.menuTally(sb,m))assert.ok(x.left===null||x.left>=0&&x.ordered<=x.limit);assert.ok(C.planWeek(sb,W).totals.prepMinutes>0);});
t('sample bakery: labels, customers and expenses are filled in',()=>{assert.ok(sb.customers.some(c=>c.allergies));assert.ok(sb.expenses.length>20);assert.ok(sb.settings.labelFooter);same(C.labelInfo(sb,sb.recipes.find(r=>r.id==='rye')).allergens,['wheat','sesame']);});
t('sample bakery: pantry stock untouched by history',()=>assert.strictEqual(sb.ingredients.find(i=>i.id==='butter').stock,1500));
t('no British spellings in the UI',()=>{const bad=ui.match(/\b(colour|favourite|totalled|organis|recognis|licence|xx)\b/gi)||[];assert.deepStrictEqual(bad.filter(w=>!/cancelled orders are left out/i.test(w)),[]);});
t('no window.confirm or alert in the UI',()=>assert.ok(!/\b(confirm|alert)\(/.test(ui.replace(/C\.\w+|ask\(/g,''))));
console.log(`${pass} passed, ${fail} failed`);process.exit(fail?1:0);
