// Bakeweek Studio keeps its own planner code, and shares the money engines with the apps on the monthly-plan core:
// the bank-statement reader (CSV + Autopilot) and invoices & purchase orders (Docs). This copies them from
// monthly-plan/app/src/core.html into Bakeweek_Studio.html between the SHARED-MONEY markers, so a fix in the core
// reaches Bakeweek on the next build.
//   node bakeweek/build.js          (from the repo root)
const fs=require('fs'),path=require('path');
const CORE=path.join(__dirname,'../monthly-plan/app/src/core.html'),APP=path.join(__dirname,'Bakeweek_Studio.html');
const core=fs.readFileSync(CORE,'utf8');
const cut=name=>{const a=core.indexOf(`const ${name} = (()=>{`),b=core.indexOf(`if(typeof module!=='undefined')module.exports=${name};`);if(a<0||b<0)throw Error(name+' not found in core.html');return core.slice(a,b).trim();};
const CURRENCIES=core.match(/const CURRENCIES=(\[[^\]]+\]);/)[1];
const block=`<script id="shared-money">
/* @@SHARED-MONEY: generated by bakeweek/build.js from monthly-plan/app/src/core.html. Edit there, not here. */
const SharedMoney=(()=>{'use strict';
// the few core helpers the statement reader leans on
const Budget={CURRENCIES:${CURRENCIES},
 today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');},
 validDate(v){if(typeof v!=='string'||!/^\\d{4}-\\d{2}-\\d{2}$/.test(v))return false;const d=new Date(v+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;}};
${cut('CSV')}
${cut('Autopilot')}
${cut('Docs')}
return {CSV,Autopilot,Docs};})();
const {CSV,Autopilot,Docs}=SharedMoney;
/* @@SHARED-MONEY end */
</script>
`;
let html=fs.readFileSync(APP,'utf8');
const re=/<script id="shared-money">[\s\S]*?\/\* @@SHARED-MONEY end \*\/\n<\/script>\n/;
if(re.test(html))html=html.replace(re,()=>block);
else{const i=html.indexOf('<script>');if(i<0)throw Error('No <script> in Bakeweek');html=html.slice(0,i)+block+html.slice(i);}
fs.writeFileSync(APP,html);
console.log(`Bakeweek: shared money engines refreshed (${Math.round(block.length/1024)} KB)`);
